// ─── Seed Data for Karnataka Government Services ─────────────────────
// 30 Verified & Seeded Services across all tiers with complete structured schemas.
import type { Service, ServiceCategory } from "@/types";

export const SEED_CATEGORIES: ServiceCategory[] = [
  { id: "cat-1", name: "Identity & Documents", slug: "identity-documents", icon: "id-card", translations: { en: "Identity & Documents", hi: "पहचान और दस्तावेज़", kn: "ಗುರುತು ಮತ್ತು ದಾಖಲೆಗಳು" }, active: true },
  { id: "cat-2", name: "Driving & Transport", slug: "driving-transport", icon: "car", translations: { en: "Driving & Transport", hi: "ड्राइविंग और परिवहन", kn: "ವಾಹನ ಮತ್ತು ಸಾರಿಗೆ" }, active: true },
  { id: "cat-3", name: "Certificates", slug: "certificates", icon: "file-check", translations: { en: "Certificates", hi: "प्रमाणपत्र", kn: "ಪ್ರಮಾಣಪತ್ರಗಳು" }, active: true },
  { id: "cat-4", name: "Voting", slug: "voting", icon: "vote", translations: { en: "Voting", hi: "मतदान", kn: "ಮತದಾನ" }, active: true },
  { id: "cat-5", name: "Property & Land", slug: "property-land", icon: "home", translations: { en: "Property & Land", hi: "संपत्ति और भूमि", kn: "ಆಸ್ತಿ ಮತ್ತು ಭೂಮಿ" }, active: true },
  { id: "cat-6", name: "Tax & Finance", slug: "tax-finance", icon: "landmark", translations: { en: "Tax & Finance", hi: "कर और वित्त", kn: "ತೆರಿಗೆ ಮತ್ತು ಹಣಕಾಸು" }, active: true },
  { id: "cat-7", name: "Employment & Benefits", slug: "employment-benefits", icon: "briefcase", translations: { en: "Employment & Benefits", hi: "रोजगार और लाभ", kn: "ಉದ್ಯೋಗ ಮತ್ತು ಸೌಲಭ್ಯಗಳು" }, active: true },
  { id: "cat-8", name: "Family & Marriage", slug: "family-marriage", icon: "heart", translations: { en: "Family & Marriage", hi: "परिवार और विवाह", kn: "ಕುಟುಂಬ ಮತ್ತು ಮದುವೆ" }, active: true },
  { id: "cat-9", name: "Police & Verification", slug: "police-verification", icon: "shield-check", translations: { en: "Police & Verification", hi: "पुलिस और सत्यापन", kn: "ಪೊಲೀಸ್ ಮತ್ತು ಪರಿಶೀಲನೆ" }, active: true },
  { id: "cat-10", name: "Health & Disability", slug: "health-disability", icon: "heart-pulse", translations: { en: "Health & Disability", hi: "स्वास्थ्य और विकलांगता", kn: "ಆರೋಗ್ಯ ಮತ್ತು ಅಂಗವೈಕಲ್ಯ" }, active: true },
  { id: "cat-11", name: "Ration & Food Security", slug: "ration-food", icon: "shopping-basket", translations: { en: "Ration & Food Security", hi: "राशन और खाद्य सुरक्षा", kn: "ಪಡಿತರ ಮತ್ತು ಆಹಾರ ಭದ್ರತೆ" }, active: true },
];

export const SEED_SERVICES: Service[] = [
  // 1. Aadhaar — New Enrollment
  {
    id: "svc-aadhaar-new-enrollment",
    slug: "aadhaar-new-enrollment",
    name: { en: "Aadhaar — New Enrollment", hi: "आधार — नया नामांकन", kn: "ಆಧಾರ್ — ಹೊಸ ನೋಂದಣಿ" },
    category: "identity-documents",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Apply for a new Aadhaar card if you do not already have one. Aadhaar is a 12-digit unique identity number issued by UIDAI to all residents of India.",
      hi: "यदि आपके पास पहले से आधार नहीं है, तो नए आधार कार्ड के लिए आवेदन करें।",
      kn: "ನಿಮ್ಮ ಬಳಿ ಆಧಾರ್ ಇಲ್ಲದಿದ್ದರೆ ಹೊಸ ಆಧಾರ್ ಕಾರ್ಡ್‌ಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    short_description: {
      en: "Get your Aadhaar number — India's universal identity document.",
      hi: "अपना आधार नंबर प्राप्त करें।",
      kn: "ನಿಮ್ಮ ಆಧಾರ್ ಸಂಖ್ಯೆ ಪಡೆಯಿರಿ.",
    },
    eligibility_rules: {
      any: [{ field: "has_aadhaar", operator: "not_equals", value: true, message: "You must not already have an Aadhaar to apply for a new one" }],
    },
    questions: [
      {
        id: "has_aadhaar",
        type: "boolean",
        label: { en: "Do you already have an Aadhaar number?", hi: "क्या आपके पास पहले से आधार नंबर है?", kn: "ನಿಮ್ಮ ಬಳಿ ಈಗಾಗಲೇ ಆಧಾರ್ ಸಂಖ್ಯೆ ಇದೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
    ],
    required_documents: [
      {
        id: "poa",
        name: { en: "Proof of Address (PoA)", hi: "पते का प्रमाण", kn: "ವಿಳಾಸ ಪುರಾವೆ" },
        status: "required",
        description: { en: "Any one: Voter ID, Passport, Bank Passbook, Utility Bill (not older than 3 months)", hi: "वोटर आईडी, पासपोर्ट, बैंक पासबुक या बिजली बिल", kn: "ಮತದಾರ ಚೀಟಿ, ಪಾಸ್‌ಪೋರ್ಟ್, ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್" },
      },
      {
        id: "poi",
        name: { en: "Proof of Identity (PoI)", hi: "पहचान का प्रमाण", kn: "ಗುರುತಿನ ಪುರಾವೆ" },
        status: "required",
        description: { en: "Any one: PAN card, Voter ID, Passport, Driving Licence", hi: "पैन कार्ड, वोटर आईडी, पासपोर्ट या ड्राइविंग लाइसेंस", kn: "ಪ್ಯಾನ್ ಕಾರ್ಡ್, ಮತದಾರ ಚೀಟಿ, ಪಾಸ್‌ಪೋರ್ಟ್" },
      },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 0,
      currency: "INR",
      is_free: true,
      notes: { en: "Aadhaar enrollment is free of charge.", hi: "आधार नामांकन निःशुल्क है।", kn: "ಆಧಾರ್ ನೋಂದಣಿ ಉಚಿತ." },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Locate Aadhaar Enrolment Centre", hi: "आधार केंद्र खोजें", kn: "ಆಧಾರ್ ಕೇಂದ್ರ ಹುಡುಕಿ" }, description: { en: "Visit uidai.gov.in to find your nearest authorised Aadhaar Seva Kendra or Bangalore One center.", hi: "uidai.gov.in पर जाएँ", kn: "uidai.gov.in ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Visit centre with original documents", hi: "मूल दस्तावेज़ों के साथ केंद्र जाएँ", kn: "ಮೂಲ ದಾಖಲೆಗಳೊಂದಿಗೆ ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ನೀಡಿ" }, description: { en: "Take original Proof of Identity and Proof of Address.", hi: "पहचान और पते के मूल प्रमाण साथ ले जाएं", kn: "ಗುರುತು ಮತ್ತು ವಿಳಾಸದ ಮೂಲ ದಾಖಲೆಗಳನ್ನು ಕೊಂಡೊಯ್ಯಿರಿ" }, is_online: false, is_offline: true },
      { step_number: 3, title: { en: "Biometric and demographic capture", hi: "बायोमेट्रिक विवरण", kn: "ಬಯೋಮೆಟ್ರಿಕ್ ವಿವರಗಳು" }, description: { en: "Fingerprints, iris scan, and photograph are captured at the counter.", hi: "फिंगरप्रिंट और फोटो खींचे जाएंगे", kn: "ಬೆರಳಚ್ಚು ಮತ್ತು ಭಾವಚಿತ್ರ ಸೆರೆಹಿಡಿಯಲಾಗುತ್ತದೆ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Receive Enrolment Slip (EID)", hi: "नामांकन पर्ची प्राप्त करें", kn: "ದಾಖಲಾತಿ ರಶೀದಿ ಪಡೆಯಿರಿ" }, description: { en: "Keep the 28-digit Enrolment ID slip safe for status tracking.", hi: "28 अंकों वाली पर्ची सुरक्षित रखें", kn: "28 ಅಂಕಿಯ EID ರಶೀದಿಯನ್ನು ಸುರಕ್ಷಿತವಾಗಿರಿಸಿ" }, is_online: false, is_offline: true },
      { step_number: 5, title: { en: "Download e-Aadhaar once generated", hi: "ई-आधार डाउनलोड करें", kn: "ಇ-ಆಧಾರ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Track and download e-Aadhaar from uidai.gov.in within 15–90 days.", hi: "uidai.gov.in से डाउनलोड करें", kn: "uidai.gov.in ನಿಂದ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://uidai.gov.in",
    official_url_label: { en: "Official UIDAI Portal", hi: "आधिकारिक UIDAI पोर्टल", kn: "ಅಧಿಕೃತ UIDAI ಪೋರ್ಟಲ್" },
    what_happens_after: {
      en: "UIDAI verifies and generates your Aadhaar in 15–90 days. You receive an SMS on your registered number. Physical card is mailed to your address.",
      hi: "UIDAI 15–90 दिनों में आपका आधार प्रोसेस करता है।",
      kn: "UIDAI 15–90 ದಿನಗಳಲ್ಲಿ ನಿಮ್ಮ ಆಧಾರ್ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ.",
    },
    troubleshooting: [
      { problem: { en: "Centre says documents insufficient", hi: "दस्तावेज़ अपर्याप्त", kn: "ದಾಖಲೆಗಳು ಸಾಲದು" }, solution: { en: "Check the approved UIDAI list of 30+ valid POI/POA documents and carry original copies.", hi: "uidai.gov.in पर स्वीकृत सूची देखें", kn: "ಅನುಮೋದಿತ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ" }, defer_to_official: false },
    ],
    source_notes: "Verified against UIDAI standards for Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["aadhaar", "aadhar", "uid", "new aadhaar", "enrollment", "uidai", "identity"],
  },

  // 2. Aadhaar — Update
  {
    id: "svc-aadhaar-update",
    slug: "aadhaar-update",
    name: { en: "Aadhaar — Update Details", hi: "आधार — विवरण अपडेट", kn: "ಆಧಾರ್ — ವಿವರ ನವೀಕರಣ" },
    category: "identity-documents",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Update your name, address, mobile number, date of birth, or biometrics on your existing Aadhaar card.",
      hi: "अपने मौजूदा आधार कार्ड पर नाम, पता, मोबाइल नंबर या बायोमेट्रिक्स अपडेट करें।",
      kn: "ನಿಮ್ಮ ಆಧಾರ್ ಕಾರ್ಡ್‌ನಲ್ಲಿ ಹೆಸರು, ವಿಳಾಸ, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಬಯೋಮೆಟ್ರಿಕ್ಸ್ ನವೀಕರಿಸಿ.",
    },
    short_description: {
      en: "Update address, mobile, name, or photo in your Aadhaar.",
      hi: "आधार में पता, मोबाइल या नाम अपडेट करें।",
      kn: "ಆಧಾರ್‌ನಲ್ಲಿ ವಿಳಾಸ ಅಥವಾ ಮೊಬೈಲ್ ಬದಲಾಯಿಸಿ.",
    },
    eligibility_rules: {
      all: [{ field: "has_aadhaar", operator: "equals", value: true, message: "You must have an existing Aadhaar number to request an update" }],
    },
    questions: [
      {
        id: "has_aadhaar",
        type: "boolean",
        label: { en: "Do you have an existing Aadhaar number?", hi: "क्या आपके पास पहले से आधार नंबर है?", kn: "ನಿಮ್ಮ ಬಳಿ ಈಗಾಗಲೇ ಆಧಾರ್ ಸಂಖ್ಯೆ ಇದೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "update_type",
        type: "select",
        label: { en: "What do you want to update?", hi: "आप क्या अपडेट करना चाहते हैं?", kn: "ನೀವು ಏನನ್ನು ನವೀಕರಿಸಲು ಬಯಸುತ್ತೀರಿ?" },
        options: [
          { value: "address", label: { en: "Address", hi: "पता", kn: "ವಿಳಾಸ" } },
          { value: "mobile", label: { en: "Mobile number", hi: "मोबाइल नंबर", kn: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ" } },
          { value: "name", label: { en: "Name / DOB / Gender", hi: "नाम / जन्म तिथि", kn: "ಹೆಸರು / ಜನ್ಮ ದಿನಾಂಕ" } },
          { value: "biometric", label: { en: "Biometrics / Photo", hi: "बायोमेट्रिक्स / फोटो", kn: "ಬಯೋಮೆಟ್ರಿಕ್ಸ್ / ಭಾವಚಿತ್ರ" } },
        ],
        required: true,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      {
        id: "aadhaar_copy",
        name: { en: "Existing Aadhaar number or card", hi: "मौजूदा आधार नंबर", kn: "ಹಾಲಿ ಆಧಾರ್ ಸಂಖ್ಯೆ" },
        status: "required",
      },
    ],
    conditional_documents: [
      {
        id: "poa_doc",
        name: { en: "Proof of Address (PoA)", hi: "पते का प्रमाण", kn: "ವಿಳಾಸ ಪುರಾವೆ" },
        status: "conditional",
        required_when: { field: "update_type", operator: "equals", value: "address" },
        description: { en: "Electricity bill, rent agreement, bank statement showing new address", hi: "नया पता दर्शाने वाला बिल या बैंक विवरण", kn: "ಹೊಸ ವಿಳಾಸ ತೋರಿಸುವ ದಾಖಲೆ" },
      },
    ],
    official_fee: {
      amount: 50,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 50 for demographic updates; Rs 100 for biometric updates.", hi: "डेमोग्राफिक के लिए 50 रुपये, बायोमेट्रिक के लिए 100 रुपये", kn: "ವಿಳಾಸಕ್ಕೆ ರೂ 50, ಬಯೋಮೆಟ್ರಿಕ್ಸ್‌ಗೆ ರೂ 100" },
      varies_by: "update_type",
    },
    steps: [
      { step_number: 1, title: { en: "Online address update or visit centre", hi: "ऑनलाइन पोर्टल या केंद्र", kn: "ಆನ್‌ಲೈನ್ ಅಥವಾ ಕೇಂದ್ರ" }, description: { en: "Address can be updated online via myaadhaar.uidai.gov.in. Mobile/biometrics require a visit to an Aadhaar Seva Kendra.", hi: "पता ऑनलाइन अपडेट हो सकता है, मोबाइल के लिए केंद्र जाएँ", kn: "ವಿಳಾಸ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು" }, is_online: true, is_offline: true },
      { step_number: 2, title: { en: "Submit supporting document & pay official fee", hi: "दस्तावेज़ जमा करें और शुल्क दें", kn: "ದಾಖಲೆ ಸಲ್ಲಿಸಿ ಶುಲ್ಕ ಪಾವತಿಸಿ" }, description: { en: "Upload valid document on the portal or present it at the counter.", hi: "पोर्टल पर अपलोड करें या काउंटर पर दें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: true },
      { step_number: 3, title: { en: "Receive Update Request Number (URN)", hi: "URN प्राप्त करें", kn: "URN ಸಂಖ್ಯೆ ಪಡೆಯಿರಿ" }, description: { en: "Track update status with URN on myaadhaar.uidai.gov.in.", hi: "URN द्वारा स्थिति ट्रैक करें", kn: "URN ನಿಂದ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://myaadhaar.uidai.gov.in",
    official_url_label: { en: "myAadhaar Portal", hi: "माईआधार पोर्टल", kn: "myAadhaar ಅಧಿಕೃತ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Updates are processed within 15–30 days. You will receive an SMS upon approval.", hi: "15–30 दिनों में अपडेट स्वीकृत होता है।", kn: "15–30 ದಿನಗಳಲ್ಲಿ ಪರಿಷ್ಕರಣೆ ಪೂರ್ಣಗೊಳ್ಳುತ್ತದೆ." },
    troubleshooting: [],
    source_notes: "UIDAI official fee and online update regulations",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["aadhaar update", "aadhar update", "change address", "change mobile", "uidai", "aadhaar correction"],
  },

  // 3. Driving Licence Renewal
  {
    id: "svc-driving-licence-renewal",
    slug: "driving-licence-renewal",
    name: { en: "Driving Licence Renewal", hi: "ड्राइविंग लाइसेंस नवीनीकरण", kn: "ಚಾಲನಾ ಪರವಾನಗಿ ನವೀಕರಣ" },
    category: "driving-transport",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Renew your expired or soon-to-expire Karnataka driving licence through Parivahan Sarathi. Valid for 10 years or up to age 50 for non-transport vehicles.",
      hi: "परिवहन सारथी पोर्टल के माध्यम से अपना समाप्त या समाप्त होने वाला ड्राइविंग लाइसेंस नवीनीकृत करें।",
      kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಮೂಲಕ ನಿಮ್ಮ ಕರ್ನಾಟಕ ಚಾಲನಾ ಪರವಾನಗಿಯನ್ನು ನವೀಕರಿಸಿ.",
    },
    short_description: {
      en: "Renew your driving licence online via Parivahan Sarathi.",
      hi: "ड्राइविंग लाइसेंस ऑनलाइन रिन्यू करें।",
      kn: "ಚಾಲನಾ ಪರವಾನಗಿ ಆನ್‌ಲೈನ್ ನವೀಕರಿಸಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "has_existing_dl", operator: "equals", value: true, message: "You must hold an existing driving licence to renew" },
      ],
    },
    questions: [
      {
        id: "has_existing_dl",
        type: "boolean",
        label: { en: "Do you have an existing Driving Licence?", hi: "क्या आपके पास मौजूदा ड्राइविंग लाइसेंस है?", kn: "ನಿಮ್ಮ ಬಳಿ ಚಾಲನಾ ಪರವಾನಗಿ ಇದೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "age_over_40",
        type: "boolean",
        label: { en: "Are you 40 years of age or older?", hi: "क्या आपकी आयु 40 वर्ष या उससे अधिक है?", kn: "ನಿಮಗೆ 40 ವರ್ಷ ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ವಯಸ್ಸಾಗಿದೆಯೇ?" },
        required: true,
        eligibility_relevant: false,
      },
      {
        id: "expired_over_year",
        type: "boolean",
        label: { en: "Has your licence been expired for more than 1 year?", hi: "क्या आपका लाइसेंस 1 वर्ष से अधिक समय से समाप्त है?", kn: "ನಿಮ್ಮ ಲೈಸೆನ್ಸ್ ಅವಧಿ ಮುಗಿದು 1 ವರ್ಷಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿದೆಯೇ?" },
        required: false,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      {
        id: "orig_dl",
        name: { en: "Original Driving Licence (or copy / Digilocker)", hi: "मूल ड्राइविंग लाइसेंस", kn: "ಮೂಲ ಚಾಲನಾ ಪರವಾನಗಿ" },
        status: "required",
      },
      {
        id: "address_proof",
        name: { en: "Proof of Address (Karnataka)", hi: "कर्नाटक पते का प्रमाण", kn: "ವಿಳಾಸ ಪುರಾವೆ" },
        status: "required",
      },
    ],
    conditional_documents: [
      {
        id: "form_1a",
        name: { en: "Medical Certificate (Form 1A signed by certified MBBS doctor)", hi: "मेडिकल सर्टिफिकेट (फॉर्म 1A)", kn: "ವೈದ್ಯಕೀಯ ಪ್ರಮಾಣಪತ್ರ (ಫಾರ್ಮ್ 1A)" },
        status: "conditional",
        required_when: { field: "age_over_40", operator: "equals", value: true },
        description: { en: "Mandatory if age is 40+ or for commercial vehicle licences.", hi: "40 वर्ष से अधिक आयु या वाणिज्यिक लाइसेंस के लिए अनिवार्य।", kn: "40 ವರ್ಷ ಮೇಲ್ಪಟ್ಟವರಿಗೆ ಕಡ್ಡಾಯ." },
      },
    ],
    official_fee: {
      amount: 450,
      currency: "INR",
      is_free: false,
      notes: { en: "Standard renewal fee Rs 400 + Smart card fee Rs 200 (Total ~Rs 450-600 depending on grace period). Additional fine if expired >1 year.", hi: "मानक नवीनीकरण शुल्क लगभग 450-600 रुपये।", kn: "ಸಾಮಾನ್ಯ ನವೀಕರಣ ಶುಲ್ಕ ರೂ 450-600." },
      varies_by: "expired_over_year",
    },
    steps: [
      { step_number: 1, title: { en: "Open Parivahan Sarathi Karnataka portal", hi: "परिवहन सारथी पोर्टल खोलें", kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ" }, description: { en: "Select Karnataka and click 'Apply for DL Services'.", hi: "कर्नाटक चुनें और DL Services पर क्लिक करें", kn: "ಕರ್ನಾಟಕ ಆಯ್ಕೆ ಮಾಡಿ 'Apply for DL Services' ಕ್ಲಿಕ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Enter DL number and Date of Birth", hi: "DL नंबर और जन्मतिथि दर्ज करें", kn: "DL ಸಂಖ್ಯೆ ಮತ್ತು ಜನ್ಮ ದಿನಾಂಕ ನಮೂದಿಸಿ" }, description: { en: "Verify your existing driving licence details on screen.", hi: "लाइसेंस विवरण सत्यापित करें", kn: "ಲೈಸೆನ್ಸ್ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Select 'Renewal of DL' service", hi: "Renewal of DL चुनें", kn: "'Renewal of DL' ಆಯ್ಕೆಮಾಡಿ" }, description: { en: "Select Renewal. If 40+, upload Form 1A Medical Certificate.", hi: "नवीनीकरण चुनें और आवश्यक होने पर फॉर्म 1A अपलोड करें", kn: "ನವೀಕರಣ ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಫಾರ್ಮ್ 1A ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 4, title: { en: "Pay government fee online", hi: "सरकारी शुल्क ऑनलाइन भरें", kn: "ಸರ್ಕಾರಿ ಶುಲ್ಕ ಆನ್‌ಲೈನ್ ಪಾವತಿಸಿ" }, description: { en: "Pay the official RTO fee through the integrated gateway.", hi: "आधिकारिक शुल्क का भुगतान करें", kn: "ಅಧಿಕೃತ RTO ಶುಲ್ಕ ಪಾವತಿಸಿ" }, is_online: true, is_offline: false },
      { step_number: 5, title: { en: "Download acknowledgement & track status", hi: "रसीद डाउनलोड करें", kn: "ರಶೀದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "In faceless RTO jurisdictions, renewed DL is dispatched by post. Otherwise visit RTO for biometric verification.", hi: "नवीनीकृत DL डाक द्वारा भेजा जाता है", kn: "ನವೀಕರಿಸಿದ DL ಅಂಚೆ ಮೂಲಕ ತಲುಪುತ್ತದೆ" }, is_online: true, is_offline: true },
    ],
    official_url: "https://sarathi.parivahan.gov.in",
    official_url_label: { en: "Parivahan Sarathi Official Portal", hi: "परिवहन सारथी आधिकारिक पोर्टल", kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಅಧಿಕೃತ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "The RTO verifies your documents within 7–15 working days. The renewed smart card is dispatched via Speed Post to your registered address.", hi: "7–15 कार्य दिवसों में RTO द्वारा अनुमोदन और डाक द्वारा स्मार्ट कार्ड प्रेषण।", kn: "7–15 ದಿನಗಳಲ್ಲಿ RTO ಅನುಮೋದನೆ ಮತ್ತು ಸ್ಪೀಡ್ ಪೋಸ್ಟ್ ಮೂಲಕ ರವಾನೆ." },
    troubleshooting: [
      { problem: { en: "DL number not found on Sarathi", hi: "सारथी पर DL नंबर नहीं मिल रहा", kn: "ಸಾರಥಿಯಲ್ಲಿ DL ಸಂಖ್ಯೆ ಕಾಣಿಸುತ್ತಿಲ್ಲ" }, solution: { en: "If your old licence was issued in a legacy non-digital book/card format, apply for 'DL Backlog Entry' first.", hi: "पहले DL Backlog Entry के लिए आवेदन करें", kn: "ಮೊದಲು DL Backlog Entry ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, defer_to_official: false },
    ],
    source_notes: "Karnataka Transport Department & Ministry of Road Transport & Highways guidelines",
    verification_status: "verified",
    last_verified_on: "2026-08-15",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-15T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["dl renewal", "driving licence renewal", "renew dl", "driving license renewal", "expired dl", "rto", "sarathi", "parivahan", "karnataka rto"],
  },

  // 4. Income Certificate (Nadakacheri / Seva Sindhu)
  {
    id: "svc-income-certificate",
    slug: "income-certificate",
    name: { en: "Income Certificate (Karnataka)", hi: "आय प्रमाणपत्र (कर्नाटक)", kn: "ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (ಕರ್ನಾಟಕ)" },
    category: "certificates",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Obtain an official Income Certificate issued by the Karnataka Revenue Department through Nadakacheri or Seva Sindhu for fee concessions, government welfare schemes, and educational scholarships.",
      hi: "कर्नाटक राजस्व विभाग से नादकचेरी या सेवा सिंधु द्वारा आय प्रमाणपत्र प्राप्त करें।",
      kn: "ನಾಡ ಕಚೇರಿ ಅಥವಾ ಸೇವಾ ಸಿಂಧು ಮೂಲಕ ಕರ್ನಾಟಕ ಕಂದಾಯ ಇಲಾಖೆಯ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ.",
    },
    short_description: {
      en: "Prove family income for Karnataka scholarships, admissions, and welfare schemes.",
      hi: "छात्रवृत्ति और सरकारी योजनाओं के लिए आय प्रमाणपत्र।",
      kn: "ವಿದ್ಯಾರ್ಥಿವೇತನ ಮತ್ತು ಯೋಜನೆಗಳಿಗೆ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ.",
    },
    eligibility_rules: {
      all: [
        { field: "is_karnataka_resident", operator: "equals", value: true, message: "Must be a resident of Karnataka" },
      ],
    },
    questions: [
      {
        id: "is_karnataka_resident",
        type: "boolean",
        label: { en: "Are you a resident of Karnataka?", hi: "क्या आप कर्नाटक के निवासी हैं?", kn: "ನೀವು ಕರ್ನಾಟಕದ ನಿವಾಸಿಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "income_source",
        type: "select",
        label: { en: "What is your primary source of family income?", hi: "आपकी आय का मुख्य स्रोत क्या है?", kn: "ನಿಮ್ಮ ಮುಖ್ಯ ಆದಾಯ ಮೂಲ ಯಾವುದು?" },
        options: [
          { value: "salary", label: { en: "Salary / Employment", hi: "वेतन / नौकरी", kn: "ವೇತನ / ನೌಕರಿ" } },
          { value: "agriculture", label: { en: "Agriculture / Farming", hi: "कृषि / खेती", kn: "ಕೃಷಿ / ಜಮೀನು" } },
          { value: "business", label: { en: "Business / Self-employed", hi: "व्यापार / स्व-रोजगार", kn: "ವ್ಯಾಪಾರ / ಸ್ವಂತ ಉದ್ಯೋಗ" } },
          { value: "daily_wage", label: { en: "Daily wage / Informal labour", hi: "दैनिक वेतन / मजदूरी", kn: "ದೈನಂದಿನ ಕೂಲಿ" } },
        ],
        required: true,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      { id: "aadhaar", name: { en: "Aadhaar Card of applicant", hi: "आवेदक का आधार कार्ड", kn: "ಅರ್ಜಿದಾರರ ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
      { id: "ration_card", name: { en: "Ration Card (BPL/APL) or Epic Card", hi: "राशन कार्ड या वोटर कार्ड", kn: "ಪಡಿತರ ಚೀಟಿ ಅಥವಾ ಮತದಾರ ಚೀಟಿ" }, status: "required" },
    ],
    conditional_documents: [
      {
        id: "salary_slip",
        name: { en: "Latest Salary Slip / Form 16", hi: "वेतन पर्ची / फॉर्म 16", kn: "ವೇತನ ಚೀಟಿ / ಫಾರ್ಮ್ 16" },
        status: "conditional",
        required_when: { field: "income_source", operator: "equals", value: "salary" },
      },
      {
        id: "land_record",
        name: { en: "RTC / Pahani Land Record", hi: "आरटीसी / भूमि रिकॉर्ड", kn: "RTC / ಪಹಾಣಿ ಭೂ ದಾಖಲೆ" },
        status: "conditional",
        required_when: { field: "income_source", operator: "equals", value: "agriculture" },
      },
    ],
    official_fee: {
      amount: 40,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 40 service charge at Nadakacheri / Seva Sindhu / Bangalore One counters.", hi: "सेवा सिंधु / नादकचेरी काउंटर पर 40 रुपये", kn: "ಸೇವಾ ಸಿಂಧು / ನಾಡ ಕಚೇರಿಯಲ್ಲಿ ರೂ 40" },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Apply on Seva Sindhu or Nadakacheri portal", hi: "सेवा सिंधु या नादकचेरी पोर्टल पर जाएँ", kn: "ಸೇವಾ ಸಿಂಧು ಅಥವಾ ನಾಡ ಕಚೇರಿ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ" }, description: { en: "Visit sevasindhu.karnataka.gov.in or nadakacheri.karnataka.gov.in.", hi: "पोर्टल पर लॉग इन करें", kn: "ಪೋರ್ಟಲ್‌ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: true },
      { step_number: 2, title: { en: "Enter applicant details & family income", hi: "आवेदक और पारिवारिक आय विवरण भरें", kn: "ಅರ್ಜಿದಾರ ಮತ್ತು ಕುಟುಂಬ ಆದಾಯ ವಿವರ ನಮೂದಿಸಿ" }, description: { en: "Provide occupation, annual declared income, and purpose of certificate.", hi: "वार्षिक आय और उद्देश्य दर्ज करें", kn: "ವಾರ್ಷಿಕ ಆದಾಯ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರದ ಉದ್ದೇಶ ತಿಳಿಸಿ" }, is_online: true, is_offline: true },
      { step_number: 3, title: { en: "Upload documents and submit", hi: "दस्तावेज़ अपलोड करें और जमा करें", kn: "ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Pay Rs 40 fee and note your GSC (Acknowledgement) number.", hi: "40 रुपये का भुगतान करें और GSC नंबर नोट करें", kn: "ರೂ 40 ಪಾವತಿಸಿ GSC ರಶೀದಿ ಸಂಖ್ಯೆ ಪಡೆಯಿರಿ" }, is_online: true, is_offline: true },
      { step_number: 4, title: { en: "Village Accountant / RI field verification", hi: "सत्यापन प्रक्रिया", kn: "ಕ್ಷೇತ್ರ ಪರಿಶೀಲನೆ" }, description: { en: "Revenue Inspector / Village Accountant reviews and recommends approval to the Tahsildar.", hi: "राजस्व निरीक्षक द्वारा रिपोर्ट तैयार की जाती है", kn: "ಕಂದಾಯ ನಿರೀಕ್ಷಕರಿಂದ ಪರಿಶೀಲನೆ" }, is_online: false, is_offline: true },
      { step_number: 5, title: { en: "Download digitally signed certificate", hi: "डिजिटल प्रमाणपत्र डाउनलोड करें", kn: "ಡಿಜಿಟಲ್ ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Download the barcode-verified certificate from Nadakacheri portal using your GSC number.", hi: "GSC नंबर से डाउनलोड करें", kn: "GSC ಸಂಖ್ಯೆ ಬಳಸಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://sevasindhu.karnataka.gov.in",
    official_url_label: { en: "Karnataka Seva Sindhu Portal", hi: "कर्नाटक सेवा सिंधु पोर्टल", kn: "ಕರ್ನಾಟಕ ಸೇವಾ ಸಿಂಧು ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "The certificate is usually issued within 7–14 working days. You can download the digitally signed PDF valid for 1 year.", hi: "7–14 कार्य दिवसों में जारी होता है, 1 वर्ष के लिए वैध।", kn: "7–14 ದಿನಗಳಲ್ಲಿ ಬಿಡುಗಡೆಯಾಗುತ್ತದೆ, 1 ವರ್ಷ ಮಾನ್ಯತೆ." },
    troubleshooting: [],
    source_notes: "Revenue Department, Government of Karnataka official citizen charter",
    verification_status: "verified",
    last_verified_on: "2026-08-10",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-10T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["income certificate", "income proof", "salary certificate", "nadakacheri", "seva sindhu", "aaya pramanapatra", "revenue karnataka"],
  },

  // 5. Voter ID (New Registration - Form 6)
  {
    id: "svc-voter-id-new",
    slug: "voter-id-new",
    name: { en: "New Voter ID Card (Form 6)", hi: "नया वोटर आईडी कार्ड (फॉर्म 6)", kn: "ಹೊಸ ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ (ಫಾರ್ಮ್ 6)" },
    category: "voting",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Register as a new voter in Karnataka through the Election Commission of India (ECI) Voters' Service Portal. Free of cost.",
      hi: "भारत निर्वाचन आयोग के पोर्टल से कर्नाटक में नए मतदाता के रूप में पंजीकरण करें।",
      kn: "ಭಾರತೀಯ ಚುನಾವಣಾ ಆಯೋಗದ ಪೋರ್ಟಲ್ ಮೂಲಕ ಕರ್ನಾಟಕದಲ್ಲಿ ಹೊಸ ಮತದಾರರಾಗಿ ನೋಂದಾಯಿಸಿ.",
    },
    short_description: {
      en: "Apply for your first Voter ID (EPIC card) on the ECI portal.",
      hi: "अपना पहला वोटर आईडी कार्ड मुफ्त बनवाएं।",
      kn: "ನಿಮ್ಮ ಮೊದಲ ಮತದಾರರ ಕಾರ್ಡ್‌ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "age_18_or_above", operator: "equals", value: true, message: "You must be 18 years of age or older" },
        { field: "is_indian_citizen", operator: "equals", value: true, message: "You must be a citizen of India" },
      ],
    },
    questions: [
      {
        id: "age_18_or_above",
        type: "boolean",
        label: { en: "Are you 18 years of age or above (or turning 18 on upcoming qualifying dates)?", hi: "क्या आप 18 वर्ष या उससे अधिक आयु के हैं?", kn: "ನೀವು 18 ವರ್ಷ ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ವಯಸ್ಸಿನವರೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "is_indian_citizen",
        type: "boolean",
        label: { en: "Are you an Indian citizen?", hi: "क्या आप भारतीय नागरिक हैं?", kn: "ನೀವು ಭಾರತೀಯ ಪ್ರಜೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
    ],
    required_documents: [
      { id: "photo", name: { en: "Recent passport-size colour photograph", hi: "पासपोर्ट आकार का फोटो", kn: "ಇತ್ತೀಚಿನ ಭಾವಚಿತ್ರ" }, status: "required" },
      { id: "age_proof", name: { en: "Proof of Age / DOB (Birth cert, 10th marksheet, Aadhaar, PAN)", hi: "आयु का प्रमाण", kn: "ವಯಸ್ಸಿನ ಪುರಾವೆ" }, status: "required" },
      { id: "address_proof", name: { en: "Proof of Residence / Address in Karnataka", hi: "कर्नाटक में निवास का प्रमाण", kn: "ಕರ್ನಾಟಕದಲ್ಲಿ ವಾಸವಿರುವ ವಿಳಾಸ ಪುರಾವೆ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 0,
      currency: "INR",
      is_free: true,
      notes: { en: "Voter registration and EPIC card issuance are 100% free of charge.", hi: "मतदाता पंजीकरण पूरी तरह निःशुल्क है।", kn: "ಮತದಾರರ ನೋಂದಣಿ ಸಂಪೂರ್ಣ ಉಚಿತ." },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Sign up on ECI Voters' Service Portal", hi: "voters.eci.gov.in पर लॉगिन करें", kn: "voters.eci.gov.in ನಲ್ಲಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ" }, description: { en: "Visit voters.eci.gov.in or download the EC Voter Helpline App.", hi: "पोर्टल पर मोबाइल नंबर से लॉगिन करें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Fill Form 6 for New Voter Registration", hi: "फॉर्म 6 भरें", kn: "ಫಾರ್ಮ್ 6 ಭರ್ತಿ ಮಾಡಿ" }, description: { en: "Select State: Karnataka, choose your Assembly Constituency, enter personal details.", hi: "राज्य कर्नाटक और अपना विधानसभा क्षेत्र चुनें", kn: "ಕರ್ನಾಟಕ ಮತ್ತು ನಿಮ್ಮ ವಿಧಾನಸಭಾ ಕ್ಷೇತ್ರ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Upload photograph, age proof, and address proof", hi: "फोटो और दस्तावेज़ अपलोड करें", kn: "ಭಾವಚಿತ್ರ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Upload clear images or PDFs under 2MB.", hi: "स्पष्ट फाइलें अपलोड करें", kn: "ಸ್ಪಷ್ಟ ಫೋಟೋ ಹಾಗೂ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 4, title: { en: "Submit and note your Reference Number", hi: "सबमिट करें और संदर्भ संख्या नोट करें", kn: "ಸಲ್ಲಿಸಿ ರೆಫರೆನ್ಸ್ ಸಂಖ್ಯೆ ಪಡೆಯಿರಿ" }, description: { en: "Use the reference number to track application progress.", hi: "ट्रैक करने के लिए संदर्भ संख्या का उपयोग करें", kn: "ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಈ ಸಂಖ್ಯೆ ಬಳಸಿ" }, is_online: true, is_offline: false },
      { step_number: 5, title: { en: "BLO field verification & EPIC delivery", hi: "बीएलओ सत्यापन और कार्ड डिलीवरी", kn: "BLO ಪರಿಶೀಲನೆ ಮತ್ತು ಕಾರ್ಡ್ ವಿತರಣೆ" }, description: { en: "Booth Level Officer (BLO) may verify your address. Physical EPIC card is delivered by Speed Post free of charge.", hi: "बीएलओ द्वारा सत्यापन के बाद कार्ड डाक द्वारा भेजा जाता है", kn: "BLO ಪರಿಶೀಲನೆಯ ನಂತರ ಕಾರ್ಡ್ ಉಚಿತವಾಗಿ ಮನೆಗೆ ತಲುಪುತ್ತದೆ" }, is_online: false, is_offline: true },
    ],
    official_url: "https://voters.eci.gov.in",
    official_url_label: { en: "ECI Voters' Service Portal", hi: "भारत निर्वाचन आयोग पोर्टल", kn: "ECI ಮತದಾರರ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "ECI processes Form 6 within 15–30 days. You can immediately download your digital e-EPIC card, and physical PVC card arrives via Speed Post.", hi: "15–30 दिनों में e-EPIC डाउनलोड के लिए तैयार और कार्ड डाक से पहुंचेगा।", kn: "15–30 ದಿನಗಳಲ್ಲಿ e-EPIC ಲಭ್ಯವಾಗುತ್ತದೆ." },
    troubleshooting: [],
    source_notes: "Election Commission of India Handbook",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["voter id", "voter card", "epic", "form 6", "election card", "voter registration", "matadara", "eci"],
  },

  // 6. Caste Certificate
  {
    id: "svc-caste-certificate",
    slug: "caste-certificate",
    name: { en: "Caste Certificate (SC/ST/OBC)", hi: "जाति प्रमाणपत्र (SC/ST/OBC)", kn: "ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ (SC/ST/OBC)" },
    category: "certificates",
    tier: 2,
    state: "karnataka",
    description: {
      en: "Obtain a Caste Certificate (SC/ST/Category 1, 2A, 2B, 3A, 3B) issued by the Karnataka Revenue Department for educational reservations and government benefits.",
      hi: "आरक्षण और सरकारी लाभों के लिए कर्नाटक राजस्व विभाग से जाति प्रमाणपत्र प्राप्त करें।",
      kn: "ಮೀಸಲಾತಿ ಮತ್ತು ಸರ್ಕಾರಿ ಸೌಲಭ್ಯಗಳಿಗಾಗಿ ಕರ್ನಾಟಕ ಕಂದಾಯ ಇಲಾಖೆಯಿಂದ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ.",
    },
    short_description: {
      en: "Get your SC/ST/OBC caste certificate for reservations and schemes.",
      hi: "आरक्षण और लाभ के लिए जाति प्रमाणपत्र।",
      kn: "ಮೀಸಲಾತಿಗಾಗಿ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ.",
    },
    eligibility_rules: {
      all: [
        { field: "is_karnataka_resident", operator: "equals", value: true, message: "Must be a resident of Karnataka" },
      ],
    },
    questions: [
      {
        id: "is_karnataka_resident",
        type: "boolean",
        label: { en: "Are you a resident of Karnataka?", hi: "क्या आप कर्नाटक के निवासी हैं?", kn: "ನೀವು ಕರ್ನಾಟಕದ ನಿವಾಸಿಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "caste_category",
        type: "select",
        label: { en: "What is your category?", hi: "आपकी श्रेणी क्या है?", kn: "ನಿಮ್ಮ ವರ್ಗ ಯಾವುದು?" },
        options: [
          { value: "sc", label: { en: "Scheduled Caste (SC)", hi: "अनुसूचित जाति (SC)", kn: "ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC)" } },
          { value: "st", label: { en: "Scheduled Tribe (ST)", hi: "अनुसूचित जनजाति (ST)", kn: "ಪರಿಶಿಷ್ಟ ಪಂಗಡ (ST)" } },
          { value: "obc", label: { en: "OBC / Cat 1 / 2A / 2B / 3A / 3B", hi: "अन्य पिछड़ा वर्ग (OBC)", kn: "ಇತರ ಹಿಂದುಳಿದ ವರ್ಗಗಳು (OBC)" } },
        ],
        required: true,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      { id: "aadhaar", name: { en: "Aadhaar Card", hi: "आधार कार्ड", kn: "ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
      { id: "ration_card", name: { en: "Ration Card or Voter ID", hi: "राशन कार्ड या वोटर आईडी", kn: "ಪಡಿತರ ಚೀಟಿ ಅಥವಾ ಮತದಾರ ಚೀಟಿ" }, status: "required" },
    ],
    conditional_documents: [
      {
        id: "family_caste_proof",
        name: { en: "Father / Mother / Sibling's Caste Certificate or School TC", hi: "माता/पिता/भाई/बहन का जाति प्रमाणपत्र या स्कूल टीसी", kn: "ಪೋಷಕರ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ ಅಥವಾ ಶಾಲಾ TC" },
        status: "conditional",
        description: { en: "Helps fast-track verification", hi: "सत्यापन को गति देता है", kn: "ತ್ವರಿತ ಪರಿಶೀಲನೆಗೆ ಸಹಕಾರಿ" },
      },
    ],
    official_fee: {
      amount: 40,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 40 fee on Seva Sindhu / Nadakacheri portal.", hi: "सेवा सिंधु / नादकचेरी पर 40 रुपये", kn: "ರೂ 40 ಶುಲ್ಕ" },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Apply on Seva Sindhu or Nadakacheri", hi: "पोर्टल पर आवेदन करें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Visit sevasindhu.karnataka.gov.in and select Caste Certificate.", hi: "सेवा सिंधु पर सेवा चुनें", kn: "ಸೇವಾ ಸಿಂಧು ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: true },
      { step_number: 2, title: { en: "Upload documents & pay fee", hi: "दस्तावेज़ अपलोड करें और शुल्क दें", kn: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಶುಲ್ಕ ಪಾವತಿಸಿ" }, description: { en: "Pay Rs 40 and note your application GSC number.", hi: "40 रुपये का भुगतान करें", kn: "ರೂ 40 ಪಾವತಿಸಿ" }, is_online: true, is_offline: true },
      { step_number: 3, title: { en: "Verification by Village Accountant & Tahsildar", hi: "सत्यापन प्रक्रिया", kn: "ಕಂದಾಯ ಇಲಾಖೆ ಪರಿಶೀಲನೆ" }, description: { en: "Revenue Inspector verifies family lineage and issues digital certificate.", hi: "राजस्व निरीक्षक द्वारा सत्यापन", kn: "ಕಂದಾಯ ನಿರೀಕ್ಷಕರಿಂದ ಪರಿಶೀಲನೆ" }, is_online: false, is_offline: true },
    ],
    official_url: "https://sevasindhu.karnataka.gov.in",
    official_url_label: { en: "Karnataka Seva Sindhu Portal", hi: "कर्नाटक सेवा सिंधु पोर्टल", kn: "ಕರ್ನಾಟಕ ಸೇವಾ ಸಿಂಧು ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Issued within 14–21 working days. Downloadable online with digital signature.", hi: "14–21 दिनों में डिजिटल हस्ताक्षरित प्रमाणपत्र जारी।", kn: "14–21 ದಿನಗಳಲ್ಲಿ ಲಭ್ಯ." },
    troubleshooting: [],
    source_notes: "Revenue Department, Government of Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["caste certificate", "sc certificate", "st certificate", "obc certificate", "nadakacheri", "jaati pramanapatra"],
  },

  // 7. Birth Certificate
  {
    id: "svc-birth-certificate",
    slug: "birth-certificate",
    name: { en: "Birth Certificate (Karnataka / e-JanMa)", hi: "जन्म प्रमाणपत्र (ई-जन्म कर्नाटक)", kn: "ಜನನ ಪ್ರಮಾಣಪತ್ರ (ಇ-ಜನ್ಮ ಕರ್ನಾಟಕ)" },
    category: "certificates",
    tier: 2,
    state: "karnataka",
    description: {
      en: "Obtain an official Birth Certificate for births registered in Karnataka via the e-JanMa portal or BBMP / Municipal Corporation.",
      hi: "ई-जन्म पोर्टल या नगर निगम द्वारा कर्नाटक में पंजीकृत जन्म का आधिकारिक प्रमाणपत्र प्राप्त करें।",
      kn: "ಇ-ಜನ್ಮ ಪೋರ್ಟಲ್ ಅಥವಾ BBMP / ಪುರಸಭೆ ಮೂಲಕ ಕರ್ನಾಟಕದಲ್ಲಿ ನೋಂದಾಯಿತ ಜನನ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ.",
    },
    short_description: {
      en: "Get or download your official birth certificate via e-JanMa Karnataka.",
      hi: "ई-जन्म पोर्टल से जन्म प्रमाणपत्र प्राप्त करें।",
      kn: "ಇ-ಜನ್ಮ ಪೋರ್ಟಲ್ ಮೂಲಕ ಜನನ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "birth_in_karnataka", operator: "equals", value: true, message: "The birth must have occurred in Karnataka" },
      ],
    },
    questions: [
      {
        id: "birth_in_karnataka",
        type: "boolean",
        label: { en: "Did the birth take place in Karnataka?", hi: "क्या जन्म कर्नाटक में हुआ था?", kn: "ಜನನವು ಕರ್ನಾಟಕದಲ್ಲಿ ನಡೆದಿದೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
    ],
    required_documents: [
      { id: "hospital_discharge", name: { en: "Hospital Discharge Summary / Birth slip from hospital", hi: "अस्पताल का जन्म प्रमाण पर्ची", kn: "ಆಸ್ಪತ್ರೆಯ ಜನನ ರಶೀದಿ" }, status: "required" },
      { id: "parent_id", name: { en: "Parents' Aadhaar / Identity proof", hi: "माता-पिता का आधार कार्ड", kn: "ಪೋಷಕರ ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 5,
      currency: "INR",
      is_free: false,
      notes: { en: "First copy free within 21 days; nominal search/print fee (Rs 5–50) thereafter.", hi: "21 दिनों के भीतर पहली प्रति निःशुल्क, बाद में मामूली शुल्क।", kn: "21 ದಿನದೊಳಗೆ ಮೊದಲ ಪ್ರತಿ ಉಚಿತ." },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Search on e-JanMa portal", hi: "e-JanMa पोर्टल पर खोजें", kn: "e-JanMa ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಹುಡುಕಿ" }, description: { en: "Visit ejanma.karnataka.gov.in and search by Date of Birth, Hospital, and Mother's name.", hi: "ejanma.karnataka.gov.in पर विवरण खोजें", kn: "ejanma.karnataka.gov.in ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Download or apply at Nadakacheri / BBMP", hi: "डाउनलोड करें या केंद्र जाएँ", kn: "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಕಚೇರಿಗೆ ಭೇಟಿ ನೀಡಿ" }, description: { en: "Download digitally signed copy or collect certified copy at Bangalore One / Nadakacheri.", hi: "प्रमाणित प्रति डाउनलोड करें", kn: "ಪ್ರಮಾಣೀಕೃತ ಪ್ರತಿಯನ್ನು ಪಡೆಯಿರಿ" }, is_online: true, is_offline: true },
    ],
    official_url: "https://ejanma.karnataka.gov.in",
    official_url_label: { en: "e-JanMa Karnataka Portal", hi: "ई-जन्म कर्नाटक पोर्टल", kn: "ಇ-ಜನ್ಮ ಕರ್ನಾಟಕ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Digitally signed certificates are instantly verified and downloadable.", hi: "तुरंत डाउनलोड और सत्यापन योग्य।", kn: "ತಕ್ಷಣ ಡೌನ್‌ಲೋಡ್ ಮಾಡಬಹುದು." },
    troubleshooting: [],
    source_notes: "e-JanMa Civil Registration System, Government of Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["birth certificate", "janma", "ejanma", "janana pramanapatra", "bbmp birth", "karnataka birth certificate"],
  },

  // 8. PAN Card — New Application (Form 49A)
  {
    id: "svc-pan-card-new",
    slug: "pan-card-new",
    name: { en: "New PAN Card (Form 49A)", hi: "नया पैन कार्ड (फॉर्म 49A)", kn: "ಹೊಸ ಪ್ಯಾನ್ ಕಾರ್ಡ್ (ಫಾರ್ಮ್ 49A)" },
    category: "identity-documents",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Apply for a 10-digit alphanumeric Permanent Account Number (PAN) issued by the Income Tax Department via NSDL (Protean) or UTIITSL.",
      hi: "आयकर विभाग द्वारा जारी नया 10 अंकों का पैन कार्ड ऑनलाइन बनवाएं।",
      kn: "ಆದಾಯ ತೆರಿಗೆ ಇಲಾಖೆಯ 10 ಅಂಕಿಯ ಹೊಸ ಪ್ಯಾನ್ ಕಾರ್ಡ್‌ಗಾಗಿ ಆನ್‌ಲೈನ್ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    short_description: {
      en: "Apply for a new Permanent Account Number (PAN) card.",
      hi: "नया पैन कार्ड ऑनलाइन बनवाएं।",
      kn: "ಹೊಸ ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಪಡೆಯಿರಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "has_pan", operator: "not_equals", value: true, message: "You must not already possess a PAN card (holding two PANs is illegal)" },
      ],
    },
    questions: [
      {
        id: "has_pan",
        type: "boolean",
        label: { en: "Do you already possess a PAN card?", hi: "क्या आपके पास पहले से पैन कार्ड है?", kn: "ನಿಮ್ಮ ಬಳಿ ಈಗಾಗಲೇ ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಇದೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
    ],
    required_documents: [
      { id: "aadhaar", name: { en: "Aadhaar Card (enables paperless e-KYC instant OTP processing)", hi: "आधार कार्ड", kn: "ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 107,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 107 for physical card dispatch within India (Free for Instant e-PAN on Income Tax e-filing portal).", hi: "फिजिकल कार्ड के लिए 107 रुपये, ई-पैन मुफ्त।", kn: "ಫಿಸಿಕಲ್ ಕಾರ್ಡ್‌ಗೆ ರೂ 107, e-PAN ಉಚಿತ." },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Go to Protean (NSDL) or Income Tax portal", hi: "NSDL या आयकर पोर्टल पर जाएँ", kn: "NSDL ಅಥವಾ ಆದಾಯ ತೆರಿಗೆ ಪೋರ್ಟಲ್‌ಗೆ ಭೇಟಿ ನೀಡಿ" }, description: { en: "Open onlineservices.nsdl.com or incometax.gov.in (Instant e-PAN).", hi: "पोर्टल पर Form 49A चुनें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ Form 49A ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Authenticate with Aadhaar OTP", hi: "आधार OTP से सत्यापित करें", kn: "ಆಧಾರ್ OTP ಯೊಂದಿಗೆ ದೃಢೀಕರಿಸಿ" }, description: { en: "Paperless e-KYC pulls photo and address directly from Aadhaar.", hi: "आधार द्वारा ऑटोमैटिक ई-केवाईसी", kn: "ಆಧಾರ್ ಮೂಲಕ ಇ-ಕೆವೈಸಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Pay government fee and receive Acknowledgement", hi: "शुल्क का भुगतान करें", kn: "ಶುಲ್ಕ ಪಾವತಿಸಿ ರಶೀದಿ ಪಡೆಯಿರಿ" }, description: { en: "Pay Rs 107 and download 15-digit acknowledgement number.", hi: "107 रुपये का भुगतान करें", kn: "ರೂ 107 ಪಾವತಿಸಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html",
    official_url_label: { en: "Protean (NSDL) PAN Portal", hi: "Protean NSDL पैन पोर्टल", kn: "Protean NSDL ಪ್ಯಾನ್ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Digital e-PAN is emailed within 24–48 hours. Physical card is dispatched via Speed Post in 10–15 days.", hi: "e-PAN 24–48 घंटों में ईमेल पर, फिजिकल कार्ड 10–15 दिनों में डाक से।", kn: "24-48 ಗಂಟೆಗಳಲ್ಲಿ ಇಮೇಲ್‌ಗೆ e-PAN, 10-15 ದಿನಗಳಲ್ಲಿ ಫಿಸಿಕಲ್ ಕಾರ್ಡ್." },
    troubleshooting: [],
    source_notes: "Income Tax Department of India guidelines",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["pan card", "pan", "form 49a", "nsdl", "utiitsl", "income tax pan", "new pan"],
  },

  // 9. Ration Card (Food & Civil Supplies - Ahara Karnataka)
  {
    id: "svc-ration-card",
    slug: "ration-card",
    name: { en: "Ration Card (BPL / APL - Ahara Karnataka)", hi: "राशन कार्ड (बीपीएल / एपीएल - आहार कर्नाटक)", kn: "ಪಡಿತರ ಚೀಟಿ (BPL / APL - ಆಹಾರ ಕರ್ನಾಟಕ)" },
    category: "ration-food",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Apply for a new Priority Household (BPL) or Non-Priority Household (APL) Ration Card via the Karnataka Food, Civil Supplies & Consumer Affairs Department (Ahara).",
      hi: "कर्नाटक खाद्य एवं नागरिक आपूर्ति विभाग (आहार) के माध्यम से नए बीपीएल/एपीएल राशन कार्ड के लिए आवेदन करें।",
      kn: "ಕರ್ನಾಟಕ ಆಹಾರ ಮತ್ತು ನಾಗರಿಕ ಸರಬರಾಜು ಇಲಾಖೆ (ಆಹಾರ) ಮೂಲಕ ಹೊಸ BPL/APL ಪಡಿತರ ಚೀಟಿಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    short_description: {
      en: "Apply for or update your Karnataka Ration Card on Ahara portal.",
      hi: "आहार पोर्टल पर राशन कार्ड के लिए आवेदन करें।",
      kn: "ಆಹಾರ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಪಡಿತರ ಚೀಟಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "is_karnataka_resident", operator: "equals", value: true, message: "Must be a resident of Karnataka" },
      ],
    },
    questions: [
      {
        id: "is_karnataka_resident",
        type: "boolean",
        label: { en: "Are you a resident of Karnataka?", hi: "क्या आप कर्नाटक के निवासी हैं?", kn: "ನೀವು ಕರ್ನಾಟಕದ ನಿವಾಸಿಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "card_type_needed",
        type: "select",
        label: { en: "Which card type are you applying for?", hi: "आप किस प्रकार के कार्ड के लिए आवेदन कर रहे हैं?", kn: "ಯಾವ ಪ್ರಕಾರದ ಪಡಿತರ ಚೀಟಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸುತ್ತಿದ್ದೀರಿ?" },
        options: [
          { value: "bpl", label: { en: "BPL (Priority Household - Annual Income < Rs 1.2 Lakhs)", hi: "बीपीएल (वार्षिक आय 1.2 लाख से कम)", kn: "BPL (ವಾರ್ಷಿಕ ಆದಾಯ ರೂ 1.2 ಲಕ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ)" } },
          { value: "apl", label: { en: "APL (Non-Priority Household)", hi: "एपीएल (गैर-प्राथमिकता)", kn: "APL (ಸಾಮಾನ್ಯ ಕುಟುಂಬ)" } },
        ],
        required: true,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      { id: "aadhaar_all", name: { en: "Aadhaar cards of all family members to be included", hi: "परिवार के सभी सदस्यों का आधार कार्ड", kn: "ಕುಟುಂಬದ ಎಲ್ಲಾ ಸದಸ್ಯರ ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
      { id: "income_cert", name: { en: "Income Certificate (Mandatory for BPL / PHH cards)", hi: "आय प्रमाणपत्र (बीपीएल के लिए अनिवार्य)", kn: "ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (BPL ಗೆ ಕಡ್ಡಾಯ)" }, status: "required" },
      { id: "address_proof", name: { en: "Electricity Bill / Gas Bill / Rental Agreement", hi: "बिजली बिल / गैस कनेक्शन", kn: "ವಿದ್ಯುತ್ ಬಿಲ್ / ವಿಳಾಸ ಪುರಾವೆ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 70,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 70 application and smart card fee at Grama One / Bangalore One / Seva Sindhu centres.", hi: "सेवा केंद्र पर 70 रुपये", kn: "ಗ್ರಾಮ ಒನ್ / ಬೆಂಗಳೂರು ಒನ್‌ನಲ್ಲಿ ರೂ 70" },
      varies_by: null,
    },
    steps: [
      { step_number: 1, title: { en: "Visit Ahara portal or Grama One / Bangalore One", hi: "आहार पोर्टल या ग्राम वन केंद्र जाएँ", kn: "ಆಹಾರ ಪೋರ್ಟಲ್ ಅಥವಾ ಗ್ರಾಮ ಒನ್ ಕೇಂದ್ರಕ್ಕೆ ಭೇಟಿ ನೀಡಿ" }, description: { en: "Open ahara.kar.nic.in during open application windows or visit your local center.", hi: "ahara.kar.nic.in पर आवेदन करें", kn: "ahara.kar.nic.in ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: true },
      { step_number: 2, title: { en: "Link Aadhaar of all members & authenticate OTP", hi: "सभी सदस्यों का आधार ओटीपी सत्यापन", kn: "ಎಲ್ಲಾ ಸದಸ್ಯರ ಆಧಾರ್ OTP ದೃಢೀಕರಣ" }, description: { en: "Every family member's Aadhaar is verified to prevent duplicates.", hi: "डुप्लीकेट रोकने के लिए आधार सत्यापन", kn: "ನಕಲು ತಡೆಯಲು ಆಧಾರ್ ಪರಿಶೀಲನೆ" }, is_online: true, is_offline: true },
      { step_number: 3, title: { en: "Field inspection by Food Inspector", hi: "खाद्य निरीक्षक द्वारा जांच", kn: "ಆಹಾರ ನಿರೀಕ್ಷಕರಿಂದ ಸ್ಥಳ ಪರಿಶೀಲನೆ" }, description: { en: "Food Inspector conducts spot verification for BPL applicants.", hi: "बीपीएल के लिए भौतिक सत्यापन", kn: "BPL ಗಾಗಿ ಸ್ಥಳ ಪರಿಶೀಲನೆ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Collect physical card / e-Ration card", hi: "राशन कार्ड प्राप्त करें", kn: "ಪಡಿತರ ಚೀಟಿ ಪಡೆಯಿರಿ" }, description: { en: "Download e-Ration Card or collect printed card from Food Department / Fair Price Shop.", hi: "ई-राशन कार्ड डाउनलोड करें", kn: "ಇ-ಪಡಿತರ ಚೀಟಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: true },
    ],
    official_url: "https://ahara.kar.nic.in",
    official_url_label: { en: "Ahara Karnataka Food Portal", hi: "आहार कर्नाटक पोर्टल", kn: "ಆಹಾರ ಕರ್ನಾಟಕ ಅಧಿಕೃತ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Application is verified within 30 days. Once approved, monthly food grains can be collected via biometric Aadhaar authentication at your assigned Fair Price Shop (FPS).", hi: "30 दिनों में सत्यापन के बाद राशन दुकान से अनाज प्राप्त किया जा सकता है।", kn: "30 ದಿನಗಳಲ್ಲಿ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಂಡು ಪಡಿತರ ಲಭ್ಯವಾಗುತ್ತದೆ." },
    troubleshooting: [],
    source_notes: "Food, Civil Supplies and Consumer Affairs Department, Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["ration card", "ahara", "bpl card", "apl card", "food security", "padithara cheeti", "karnataka ration"],
  },

  // 10. Passport (Passport Seva Kendra)
  {
    id: "svc-passport",
    slug: "passport",
    name: { en: "Passport (Fresh / Re-issue)", hi: "पासपोर्ट (नया / नवीनीकरण)", kn: "ಪಾಸ್‌ಪೋರ್ಟ್ (ಹೊಸ / ನವೀಕರಣ)" },
    category: "identity-documents",
    tier: 1,
    state: "karnataka",
    description: {
      en: "Apply for a fresh Indian Passport or re-issue of an expiring passport through the Ministry of External Affairs Passport Seva portal for appointment at PSK Bengaluru, Mangaluru, Hubballi, etc.",
      hi: "विदेश मंत्रालय के पासपोर्ट सेवा पोर्टल से नया पासपोर्ट बनवाएं या नवीनीकरण कराएं।",
      kn: "ವಿದೇಶಾಂಗ ಸಚಿವಾಲಯದ ಪಾಸ್‌ಪೋರ್ಟ್ ಸೇವಾ ಪೋರ್ಟಲ್ ಮೂಲಕ ಪಾಸ್‌ಪೋರ್ಟ್‌ಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    short_description: {
      en: "Apply for a new or renewed Indian passport via Passport Seva.",
      hi: "नया या रिन्यू पासपोर्ट ऑनलाइन अप्लाई करें।",
      kn: "ಹೊಸ ಅಥವಾ ನವೀಕೃತ ಪಾಸ್‌ಪೋರ್ಟ್‌ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    },
    eligibility_rules: {
      all: [
        { field: "is_indian_citizen", operator: "equals", value: true, message: "Must be a citizen of India" },
      ],
    },
    questions: [
      {
        id: "is_indian_citizen",
        type: "boolean",
        label: { en: "Are you an Indian citizen?", hi: "क्या आप भारतीय नागरिक हैं?", kn: "ನೀವು ಭಾರತೀಯ ಪ್ರಜೆಯೇ?" },
        required: true,
        eligibility_relevant: true,
      },
      {
        id: "application_type",
        type: "select",
        label: { en: "Are you applying under Normal or Tatkaal scheme?", hi: "क्या आप सामान्य या तत्काल योजना के तहत आवेदन कर रहे हैं?", kn: "ಸಾಮಾನ್ಯ ಅಥವಾ ತತ್ಕಾಲ್ ಯೋಜನೆಯಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸುತ್ತಿದ್ದೀರಾ?" },
        options: [
          { value: "normal", label: { en: "Normal (Regular processing)", hi: "सामान्य (Normal)", kn: "ಸಾಮಾನ್ಯ (Normal)" } },
          { value: "tatkaal", label: { en: "Tatkaal (Urgent processing)", hi: "तत्काल (Tatkaal)", kn: "ತತ್ಕಾಲ್ (Tatkaal)" } },
        ],
        required: true,
        eligibility_relevant: false,
      },
    ],
    required_documents: [
      { id: "dob_proof", name: { en: "Proof of Date of Birth (Birth cert, 10th marksheet, PAN, Aadhaar)", hi: "जन्मतिथि का प्रमाण", kn: "ಜನ್ಮ ದಿನಾಂಕ ಪುರಾವೆ" }, status: "required" },
      { id: "address_proof", name: { en: "Proof of Present Address (Aadhaar, Bank Passbook, Utility Bill)", hi: "वर्तमान पते का प्रमाण", kn: "ಪ್ರಸ್ತುತ ವಿಳಾಸ ಪುರಾವೆ" }, status: "required" },
      { id: "non_ecr_proof", name: { en: "Educational Certificate (10th standard pass or higher for Non-ECR)", hi: "10वीं की अंकतालिका (Non-ECR के लिए)", kn: "10ನೇ ತರಗತಿ ಪ್ರಮಾಣಪತ್ರ (Non-ECR ಗೆ)" }, status: "optional" },
    ],
    conditional_documents: [],
    official_fee: {
      amount: 1500,
      currency: "INR",
      is_free: false,
      notes: { en: "Rs 1,500 for Normal 36-page booklet; Rs 3,500 for Tatkaal. Payable online at passportindia.gov.in.", hi: "सामान्य के लिए 1,500 रुपये, तत्काल के लिए 3,500 रुपये।", kn: "ಸಾಮಾನ್ಯಕ್ಕೆ ರೂ 1,500, ತತ್ಕಾಲ್‌ಗೆ ರೂ 3,500." },
      varies_by: "application_type",
    },
    steps: [
      { step_number: 1, title: { en: "Register on Passport Seva Portal", hi: "passportindia.gov.in पर रजिस्टर करें", kn: "passportindia.gov.in ನಲ್ಲಿ ನೋಂದಾಯಿಸಿ" }, description: { en: "Create account on passportindia.gov.in and choose nearest RPO (e.g. Bengaluru).", hi: "खाता बनाएं और फॉर्म भरें", kn: "ಖಾತೆ ರಚಿಸಿ ಅರ್ಜಿ ಭರ್ತಿ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Fill Application & Pay Fee online", hi: "शुल्क का ऑनलाइन भुगतान करें", kn: "ಆನ್‌ಲೈನ್ ಶುಲ್ಕ ಪಾವತಿಸಿ" }, description: { en: "Pay Rs 1,500 and book appointment slot at your nearest PSK / POPSK.", hi: "शुल्क भरें और अपॉइंटमेंट स्लॉट बुक करें", kn: "ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Visit Passport Seva Kendra (PSK) with original documents", hi: "मूल दस्तावेज़ों के साथ PSK जाएँ", kn: "ಮೂಲ ದಾಖಲೆಗಳೊಂದಿಗೆ PSK ಗೆ ಭೇಟಿ ನೀಡಿ" }, description: { en: "Complete document verification, photo capture, and biometrics at counters A, B, C.", hi: "बायोमेट्रिक और दस्तावेज़ सत्यापन", kn: "ದಾಖಲೆ ಮತ್ತು ಬಯೋಮೆಟ್ರಿಕ್ ಪರಿಶೀಲನೆ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Police Verification at local police station", hi: "स्थानीय पुलिस सत्यापन", kn: "ಸ್ಥಳೀಯ ಪೊಲೀಸ್ ಪರಿಶೀಲನೆ" }, description: { en: "Local police station contacts you for address and identity verification.", hi: "थाने में भौतिक सत्यापन", kn: "ಠಾಣೆಯಲ್ಲಿ ವಿಳಾಸ ದೃಢೀಕರಣ" }, is_online: false, is_offline: true },
      { step_number: 5, title: { en: "Passport printing & Speed Post delivery", hi: "पासपोर्ट स्पीड पोस्ट से डिलीवरी", kn: "ಸ್ಪೀಡ್ ಪೋಸ್ಟ್ ಮೂಲಕ ಪಾಸ್‌ಪೋರ್ಟ್ ವಿತರಣೆ" }, description: { en: "Passport is printed and dispatched directly to your address via Speed Post.", hi: "पासपोर्ट सीधे आपके पते पर भेजा जाता है", kn: "ಪಾಸ್‌ಪೋರ್ಟ್ ನಿಮ್ಮ ಮನೆ ವಿಳಾಸಕ್ಕೆ ತಲುಪುತ್ತದೆ" }, is_online: false, is_offline: true },
    ],
    official_url: "https://www.passportindia.gov.in",
    official_url_label: { en: "Passport Seva Official Portal", hi: "पासपोर्ट सेवा आधिकारिक पोर्टल", kn: "ಪಾಸ್‌ಪೋರ್ಟ್ ಸೇವಾ ಅಧಿಕೃತ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Normal passports are delivered in 15–20 working days following police clearance. Tatkaal passports are dispatched in 1–3 days.", hi: "सामान्य पासपोर्ट 15–20 दिनों में, तत्काल 1–3 दिनों में।", kn: "ಸಾಮಾನ್ಯ ಪಾಸ್‌ಪೋರ್ಟ್ 15-20 ದಿನಗಳಲ್ಲಿ ತಲುಪುತ್ತದೆ." },
    troubleshooting: [],
    source_notes: "Ministry of External Affairs, Government of India",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["passport", "psk", "passport renewal", "tatkaal passport", "passport seva", "mea", "rpo bangalore"],
  },

  // 11. Learner's Licence (LL)
  {
    id: "svc-learners-licence",
    slug: "learners-licence",
    name: { en: "Learner's Licence (LL)", hi: "लर्नर लाइसेंस (LL)", kn: "ಕಲಿಕಾ ಪರವಾನಗಿ (LL)" },
    category: "driving-transport",
    tier: 1,
    state: "karnataka",
    description: { en: "Apply for a Learner's Licence for two-wheelers or light motor vehicles (LMV) via contactless online test on Parivahan Sarathi.", hi: "परिवहन सारथी पर ऑनलाइन टेस्ट देकर लर्नर लाइसेंस प्राप्त करें।", kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಮೂಲಕ ಆನ್‌ಲೈನ್ ಟೆಸ್ಟ್ ನೀಡಿ ಕಲಿಕಾ ಪರವಾನಗಿ ಪಡೆಯಿರಿ." },
    short_description: { en: "Apply for your first Learner's Licence online via Parivahan Sarathi.", hi: "लर्नर लाइसेंस ऑनलाइन बनवाएं।", kn: "ಕಲಿಕಾ ಪರವಾನಗಿಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ." },
    eligibility_rules: {
      all: [
        { field: "age_16_or_above", operator: "equals", value: true, message: "Must be at least 16 years for gearless two-wheeler, or 18 for LMV/car" },
      ],
    },
    questions: [
      { id: "age_16_or_above", type: "boolean", label: { en: "Are you 16 years of age or older?", hi: "क्या आप 16 वर्ष या उससे अधिक हैं?", kn: "ನೀವು 16 ವರ್ಷ ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ವಯಸ್ಸಿನವರೇ?" }, required: true, eligibility_relevant: true },
      { id: "vehicle_class", type: "select", label: { en: "Which vehicle type do you want to learn?", hi: "आप किस वाहन के लिए आवेदन कर रहे हैं?", kn: "ಯಾವ ವಾಹನಕ್ಕಾಗಿ ಕಲಿಯಲು ಬಯಸುತ್ತೀರಿ?" }, options: [{ value: "mcwg", label: { en: "Motorcycle with Gear (2-wheeler)", hi: "मोटरसाइकिल (गियर वाली)", kn: "ದ್ವಿಚಕ್ರ ವಾಹನ (ಗೇರ್)" } }, { value: "lmv", label: { en: "Light Motor Vehicle / Car", hi: "कार / एलएमवी", kn: "ಕಾರು / LMV" } }], required: true, eligibility_relevant: false },
    ],
    required_documents: [
      { id: "aadhaar", name: { en: "Aadhaar Card (enables faceless online LL test from home)", hi: "आधार कार्ड", kn: "ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
      { id: "age_proof", name: { en: "Proof of Age / 10th standard certificate", hi: "आयु का प्रमाण", kn: "ವಯಸ್ಸಿನ ಪುರಾವೆ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 200, currency: "INR", is_free: false, notes: { en: "Rs 150 per vehicle class + Rs 50 test fee.", hi: "प्रति क्लास 150 रुपये + 50 रुपये टेस्ट शुल्क", kn: "ರೂ 200 ಅಧಿಕೃತ ಶುಲ್ಕ." }, varies_by: null },
    steps: [
      { step_number: 1, title: { en: "Apply on Sarathi with Aadhaar authentication", hi: "सारथी पोर्टल पर आधार से अप्लाई करें", kn: "ಸಾರಥಿ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಆಧಾರ್ ದೃಢೀಕರಣದೊಂದಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Visit sarathi.parivahan.gov.in, select Karnataka and 'Application for LL'.", hi: "sarathi.parivahan.gov.in पर जाएं", kn: "sarathi.parivahan.gov.in ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Pay fee & watch Road Safety video", hi: "शुल्क भरें और वीडियो देखें", kn: "ಶುಲ್ಕ ಪಾವತಿಸಿ ರಸ್ತೆ ಸುರಕ್ಷತಾ ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ" }, description: { en: "Watch mandatory road safety tutorial online.", hi: "अनिवार्य रोड सेफ्टी ट्यूटोरियल देखें", kn: "ರಸ್ತೆ ಸುರಕ್ಷತೆ ವಿಡಿಯೋ ನೋಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Pass online LL computer test from home", hi: "घर बैठे ऑनलाइन टेस्ट पास करें", kn: "ಮನೆಯಿಂದಲೇ ಆನ್‌ಲೈನ್ ಪರೀಕ್ಷೆ ಪಾಸು ಮಾಡಿ" }, description: { en: "Answer 15 traffic signs & road rules questions (pass mark 9/15).", hi: "15 में से 9 प्रश्न सही उत्तर दें", kn: "15 ಪ್ರಶ್ನೆಗಳಲ್ಲಿ 9 ಸರಿ ಉತ್ತರ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 4, title: { en: "Instantly download digital Learner's Licence", hi: "लर्नर लाइसेंस डाउनलोड करें", kn: "ಕಲಿಕಾ ಪರವಾನಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Valid across India for 6 months. Eligible for permanent DL after 30 days.", hi: "6 महीने के लिए वैध", kn: "6 ತಿಂಗಳವರೆಗೆ ಮಾನ್ಯತೆ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://sarathi.parivahan.gov.in",
    official_url_label: { en: "Parivahan Sarathi Portal", hi: "सारथी पोर्टल", kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "LL is generated immediately upon passing test. You can apply for Permanent Driving Licence after 30 days.", hi: "टेस्ट पास होते ही तुरंत डाउनलोड योग्य। 30 दिन बाद पक्के DL के लिए आवेदन करें।", kn: "ಟೆಸ್ಟ್ ಮುಗಿದ ತಕ್ಷಣ LL ಲಭ್ಯ. 30 ದಿನಗಳ ನಂತರ ಪರ್ಮನೆಂಟ್ DL ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ." },
    troubleshooting: [],
    source_notes: "Karnataka Motor Vehicles Rules",
    verification_status: "verified",
    last_verified_on: "2026-08-15",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-15T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["learners licence", "learner license", "ll", "learning licence", "rto", "sarathi", "driving test"],
  },

  // 12. Permanent Driving Licence (DL)
  {
    id: "svc-permanent-driving-licence",
    slug: "permanent-driving-licence",
    name: { en: "Permanent Driving Licence (DL)", hi: "स्थायी ड्राइविंग लाइसेंस (DL)", kn: "ಖಾಯಂ ಚಾಲನಾ ಪರವಾನಗಿ (DL)" },
    category: "driving-transport",
    tier: 1,
    state: "karnataka",
    description: { en: "Apply for a permanent Driving Licence after holding an active Learner's Licence for at least 30 days.", hi: "30 दिन का लर्नर लाइसेंस होने के बाद स्थायी ड्राइविंग लाइसेंस के लिए आवेदन करें।", kn: "ಕನಿಷ್ಠ 30 ದಿನಗಳ LL ಹೊಂದಿದ ನಂತರ ಖಾಯಂ ಚಾಲನಾ ಪರವಾನಗಿಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ." },
    short_description: { en: "Book driving test and get your permanent smart card DL.", hi: "ड्राइविंग टेस्ट बुक करें और पक्का लाइसेंस प्राप्त करें।", kn: "ಡ್ರೈವಿಂಗ್ ಟೆಸ್ಟ್ ಬುಕ್ ಮಾಡಿ ಖಾಯಂ DL ಪಡೆಯಿರಿ." },
    eligibility_rules: {
      all: [
        { field: "has_valid_ll", operator: "equals", value: true, message: "Must have an active Learner's Licence held for at least 30 days" },
      ],
    },
    questions: [
      { id: "has_valid_ll", type: "boolean", label: { en: "Do you have an active Learner's Licence (LL) issued at least 30 days ago?", hi: "क्या आपके पास कम से कम 30 दिन पुराना वैध LL है?", kn: "ನಿಮ್ಮ ಬಳಿ ಕನಿಷ್ಠ 30 ದಿನಗಳ ಹಳೆಯ ಚಾಲ್ತಿಯಲ್ಲಿರುವ LL ಇದೆಯೇ?" }, required: true, eligibility_relevant: true },
    ],
    required_documents: [
      { id: "ll_copy", name: { en: "Active Learner's Licence copy", hi: "लर्नर लाइसेंस की प्रति", kn: "ಚಾಲ್ತಿಯಲ್ಲಿರುವ LL ಪ್ರತಿ" }, status: "required" },
      { id: "form_5", name: { en: "Driving School Certificate (Form 5) if trained at school", hi: "ड्राइविंग स्कूल प्रमाण पत्र", kn: "ಡ್ರೈವಿಂಗ್ ಸ್ಕೂಲ್ ಪ್ರಮಾಣಪತ್ರ" }, status: "optional" },
    ],
    conditional_documents: [],
    official_fee: { amount: 650, currency: "INR", is_free: false, notes: { en: "Rs 200 DL issue + Rs 300 test fee + Rs 200 Smart card fee.", hi: "कुल 650-700 रुपये", kn: "ರೂ 650 ಅಧಿಕೃತ ಶುಲ್ಕ." }, varies_by: null },
    steps: [
      { step_number: 1, title: { en: "Apply for Driving Licence on Sarathi", hi: "सारथी पोर्टल पर आवेदन करें", kn: "ಸಾರಥಿ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Enter your LL number and date of birth.", hi: "LL नंबर दर्ज करें", kn: "LL ಸಂಖ್ಯೆ ನಮೂದಿಸಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Book RTO Driving Test Slot", hi: "ड्राइविंग टेस्ट स्लॉट बुक करें", kn: "RTO ಡ್ರೈವಿಂಗ್ ಟೆಸ್ಟ್ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ" }, description: { en: "Choose your convenient date at the assigned RTO track.", hi: "RTO ट्रैक पर तारीख चुनें", kn: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Take physical driving test at RTO track", hi: "RTO ट्रैक पर टेस्ट दें", kn: "RTO ಟ್ರ್ಯಾಕ್‌ನಲ್ಲಿ ಪರೀಕ್ಷೆ ನೀಡಿ" }, description: { en: "Demonstrate vehicle driving skills to the Motor Vehicles Inspector (MVI).", hi: "मोटर वाहन निरीक्षक के सामने टेस्ट पास करें", kn: "MVI ಅವರ ಮುಂದೆ ಡ್ರೈವಿಂಗ್ ಕೌಶಲ್ಯ ಪ್ರದರ್ಶಿಸಿ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Smart Card DL dispatched by Speed Post", hi: "स्मार्ट कार्ड डाक से पहुंचेगा", kn: "ಸ್ಮಾರ್ಟ್ ಕಾರ್ಡ್ ಅಂಚೆ ಮೂಲಕ ತಲುಪುತ್ತದೆ" }, description: { en: "Upon passing, DL smart card is printed and posted within 10–15 days.", hi: "10-15 दिनों में घर पहुंचेगा", kn: "10-15 ದಿನಗಳಲ್ಲಿ ಮನೆಗೆ ತಲುಪುತ್ತದೆ" }, is_online: false, is_offline: true },
    ],
    official_url: "https://sarathi.parivahan.gov.in",
    official_url_label: { en: "Parivahan Sarathi Portal", hi: "सारथी पोर्टल", kn: "ಪರಿವಾಹನ ಸಾರಥಿ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "MVI approves your result on the same day. Smart card DL arrives via Speed Post within 2 weeks.", hi: "2 सप्ताह में स्मार्ट कार्ड DL डाक द्वारा प्राप्त होगा।", kn: "2 ವಾರಗಳಲ್ಲಿ ಸ್ಮಾರ್ಟ್ ಕಾರ್ಡ್ ಮನೆಗೆ ತಲುಪುತ್ತದೆ." },
    troubleshooting: [],
    source_notes: "Karnataka Transport Department",
    verification_status: "verified",
    last_verified_on: "2026-08-15",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-15T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["permanent dl", "driving licence", "driving license", "rto test", "sarathi", "karnataka driving licence"],
  },

  // 13. Khata Certificate / Transfer (BBMP)
  {
    id: "svc-khata-certificate-transfer",
    slug: "khata-certificate-transfer",
    name: { en: "Khata Certificate / Transfer (BBMP)", hi: "खाता प्रमाणपत्र / खाता स्थानांतरण (BBMP)", kn: "ಖಾತಾ ಪ್ರಮಾಣಪತ್ರ / ಖಾತಾ ವರ್ಗಾವಣೆ (BBMP)" },
    category: "property-land",
    tier: 3,
    state: "karnataka",
    description: { en: "Apply for BBMP e-Khata extract or Khata ownership transfer for properties in Bengaluru via Seva Sindhu or BBMP portal.", hi: "बेंगलुरु में BBMP संपत्तियों के लिए ई-खाता या खाता ट्रांसफर के लिए आवेदन करें।", kn: "ಬೆಂಗಳೂರಿನಲ್ಲಿ BBMP ಆಸ್ತಿಗಳಿಗೆ ಇ-ಖಾತಾ ಅಥವಾ ಖಾತಾ ವರ್ಗಾವಣೆಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ." },
    short_description: { en: "Get your BBMP property e-Khata or transfer ownership online.", hi: "BBMP ई-खाता या ट्रांसफर कराएं।", kn: "BBMP ಇ-ಖಾತಾ ಅಥವಾ ವರ್ಗಾವಣೆ ಮಾಡಿಸಿಕೊಳ್ಳಿ." },
    eligibility_rules: null,
    questions: [
      { id: "service_type", type: "select", label: { en: "What do you need?", hi: "आपको क्या चाहिए?", kn: "ನಿಮಗೆ ಏನು ಬೇಕು?" }, options: [{ value: "extract", label: { en: "Khata Extract / Certificate", hi: "खाता सर्टिफिकेट", kn: "ಖಾತಾ ಪ್ರಮಾಣಪತ್ರ" } }, { value: "transfer", label: { en: "Khata Transfer (New owner)", hi: "खाता ट्रांसफर", kn: "ಖಾತಾ ವರ್ಗಾವಣೆ" } }], required: true, eligibility_relevant: false },
    ],
    required_documents: [
      { id: "sale_deed", name: { en: "Registered Sale Deed / Title Deed", hi: "पंजीकृत बिक्री विलेख", kn: "ನೋಂದಾಯಿತ ಮಾರಾಟ ಪತ್ರ" }, status: "required" },
      { id: "tax_receipts", name: { en: "Latest Property Tax Paid Receipt", hi: "नवीनतम संपत्ति कर रसीद", kn: "ಇತ್ತೀಚಿನ ಆಸ್ತಿ ತೆರಿಗೆ ಪಾವತಿ ರಶೀದಿ" }, status: "required" },
      { id: "encumbrance", name: { en: "Encumbrance Certificate (EC) for 15+ years", hi: "भार प्रमाणपत्र (EC)", kn: "ಅಡಮಾನ ಪ್ರಮಾಣಪತ್ರ (EC)" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: null, currency: "INR", is_free: false, notes: { en: "2% of stamp duty value for transfer fee + Rs 125 per certificate copy.", hi: "स्टाम्प वैल्यू का 2% + प्रति कॉपी 125 रुपये", kn: "ಸ್ಟಾಂಪ್ ಡ್ಯೂಟಿಯ 2% ವರ್ಗಾವಣೆ ಶುಲ್ಕ + ಪ್ರತಿ ಪ್ರತಿಯಂತೆ ರೂ 125." }, varies_by: "property_value" },
    steps: [
      { step_number: 1, title: { en: "Apply on Seva Sindhu or BBMP e-Khata portal", hi: "सेवा सिंधु पर ई-खाता आवेदन करें", kn: "ಸೇವಾ ಸಿಂಧು ಅಥವಾ BBMP ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Select BBMP Khata Transfer / Extract service.", hi: "BBMP Khata सेवा चुनें", kn: "BBMP Khata ಸೇವೆ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Upload property deed and EC", hi: "दस्तावेज़ अपलोड करें", kn: "ಮಾರಾಟ ಪತ್ರ ಮತ್ತು EC ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Upload scanned copies of registered sale deed and EC.", hi: "बिक्री विलेख और ईसी अपलोड करें", kn: "ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Assistant Revenue Officer (ARO) approval", hi: "सहायक राजस्व अधिकारी द्वारा स्वीकृति", kn: "ಸಹಾಯಕ ಕಂದಾಯ ಅಧಿಕಾರಿ (ARO) ಪರಿಶೀಲನೆ" }, description: { en: "Pay calculated transfer fee and download digitally signed e-Khata certificate.", hi: "शुल्क का भुगतान करें और डाउनलोड करें", kn: "ಶುಲ್ಕ ಪಾವತಿಸಿ ಇ-ಖಾತಾ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://bbmptax.karnataka.gov.in",
    official_url_label: { en: "BBMP Property Portal", hi: "BBMP संपत्ति पोर्टल", kn: "BBMP ಆಸ್ತಿ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "BBMP processes Khata transfer in 30 working days. Digitally signed e-Khata certificate is generated with a unique QR code.", hi: "30 कार्य दिवसों में ई-खाता जारी।", kn: "30 ದಿನಗಳಲ್ಲಿ QR ಕೋಡ್ ಹೊಂದಿರುವ ಇ-ಖಾತಾ ಬಿಡುಗಡೆ." },
    troubleshooting: [],
    source_notes: "BBMP Revenue Department circulars",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["khata", "khata certificate", "khata transfer", "bbmp khata", "e-khata", "bengaluru property", "a-khata", "b-khata"],
  },

  // 14. Encumbrance Certificate (EC - Kaveri Online)
  {
    id: "svc-encumbrance-certificate",
    slug: "encumbrance-certificate",
    name: { en: "Encumbrance Certificate (EC - Kaveri Online)", hi: "भार प्रमाणपत्र (EC - कावेरी ऑनलाइन)", kn: "ಅಡಮಾನ ಪ್ರಮಾಣಪತ್ರ (EC - ಕಾವೇರಿ ಆನ್‌ಲೈನ್)" },
    category: "property-land",
    tier: 3,
    state: "karnataka",
    description: { en: "Search and download digitally signed Encumbrance Certificate (Form 15 or 16) for any Karnataka property on Kaveri Online Services.", hi: "कावेरी ऑनलाइन पोर्टल से किसी भी संपत्ति का भार प्रमाणपत्र (EC) ऑनलाइन डाउनलोड करें।", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್ ಪೋರ್ಟಲ್ ಮೂಲಕ ಯಾವುದೇ ಕರ್ನಾಟಕ ಆಸ್ತಿಯ ಅಡಮಾನ ಪ್ರಮಾಣಪತ್ರ (EC) ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ." },
    short_description: { en: "Search property transaction history and download EC on Kaveri.", hi: "कावेरी पोर्टल पर प्रॉपर्टी का EC तुरंत डाउनलोड करें।", kn: "ಕಾವೇರಿ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ತಕ್ಷಣ EC ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ." },
    eligibility_rules: null,
    questions: [],
    required_documents: [
      { id: "property_details", name: { en: "Property details (Survey No / Plot No / Sub-registrar office)", hi: "संपत्ति विवरण (सर्वे नंबर या पता)", kn: "ಆಸ್ತಿ ವಿವರಗಳು (ಸರ್ವೆ ಸಂಖ್ಯೆ ಅಥವಾ ನೋಂದಣಿ ಕಚೇರಿ)" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 50, currency: "INR", is_free: false, notes: { en: "Rs 50 application fee + nominal search fee based on period of years.", hi: "50 रुपये + सर्च शुल्क", kn: "ರೂ 50 ಅರ್ಜಿ ಶುಲ್ಕ + ಅವಧಿ ಆಧಾರಿತ ಹುಡುಕಾಟ ಶುಲ್ಕ." }, varies_by: "years" },
    steps: [
      { step_number: 1, title: { en: "Login to Kaveri Online Services", hi: "कावेरी पोर्टल पर लॉगिन करें", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್ ಪೋರ್ಟಲ್‌ಗೆ ಲಾಗಿನ್ ಮಾಡಿ" }, description: { en: "Visit kaverionline.karnataka.gov.in and select 'Online EC'.", hi: "kaverionline.karnataka.gov.in पर जाएँ", kn: "kaverionline.karnataka.gov.in ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Enter property search parameters", hi: "संपत्ति का विवरण दर्ज करें", kn: "ಆಸ್ತಿ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ" }, description: { en: "Select District, SRO office, Village, and Survey / House Number.", hi: "जिला, उप-पंजीयक कार्यालय और सर्वे नंबर चुनें", kn: "ಜಿಲ್ಲೆ, ಉಪನೋಂದಣಾಧಿಕಾರಿ ಕಚೇರಿ ಮತ್ತು ಸರ್ವೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Pay fee and instantly download signed EC", hi: "शुल्क देकर डाउनलोड करें", kn: "ಶುಲ್ಕ ಪಾವತಿಸಿ ತಕ್ಷಣ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Download digitally signed PDF certificate.", hi: "डिजिटल हस्ताक्षरित PDF डाउनलोड करें", kn: "ಡಿಜಿಟಲ್ ಸಹಿ ಇರುವ PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://kaverionline.karnataka.gov.in",
    official_url_label: { en: "Kaveri Online Services Portal", hi: "कावेरी ऑनलाइन पोर्टल", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್ ಸೇವೆಗಳ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Digitally signed EC is generated instantly for digitized years (2004 onwards). For older manual records, physical verification takes 3–5 days.", hi: "2004 के बाद के रिकॉर्ड तुरंत डाउनलोड होते हैं।", kn: "2004 ರ ನಂತರದ ದಾಖಲೆಗಳು ತಕ್ಷಣ ಲಭ್ಯ." },
    troubleshooting: [],
    source_notes: "Department of Stamps and Registration, Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["ec", "encumbrance certificate", "kaveri", "kaveri online", "property ec", "form 15", "sub registrar karnataka"],
  },

  // 15. RTC / Pahani Land Records (Bhoomi Karnataka)
  {
    id: "svc-rtc-pahani",
    slug: "rtc-pahani",
    name: { en: "RTC / Pahani (Bhoomi Karnataka Land Records)", hi: "आरटीसी / पहानी (भूमि कर्नाटक भूमि रिकॉर्ड)", kn: "ಆರ್‌ಟಿಸಿ / ಪಹಾಣಿ (ಭೂಮಿ ಕರ್ನಾಟಕ ಭೂ ದಾಖಲೆಗಳು)" },
    category: "property-land",
    tier: 3,
    state: "karnataka",
    description: { en: "View and download official Record of Rights, Tenancy and Crops (RTC / Pahani) for agricultural land in Karnataka via Bhoomi portal.", hi: "भूमि पोर्टल से कर्नाटक में कृषि भूमि का आरटीसी / पहानी रिकॉर्ड देखें और डाउनलोड करें।", kn: "ಭೂಮಿ ಪೋರ್ಟಲ್ ಮೂಲಕ ಕರ್ನಾಟಕದ ಕೃಷಿ ಭೂಮಿಯ ಅಧಿಕೃತ ಆರ್‌ಟಿಸಿ / ಪಹಾಣಿ ದಾಖಲೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ." },
    short_description: { en: "Download official land RTC (Pahani) on Bhoomi Karnataka.", hi: "भूमि पोर्टल से खेत की खतौनी / आरटीसी डाउनलोड करें।", kn: "ಭೂಮಿ ಪೋರ್ಟಲ್‌ನಿಂದ ಆರ್‌ಟಿಸಿ ಪಹಾಣಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ." },
    eligibility_rules: null,
    questions: [],
    required_documents: [
      { id: "land_details", name: { en: "District, Taluk, Hobli, Village & Survey Number", hi: "जिला, तालुक, गांव और सर्वे नंबर", kn: "ಜಿಲ್ಲೆ, ತಾಲೂಕು, ಹೋಬಳಿ, ಗ್ರಾಮ ಮತ್ತು ಸರ್ವೆ ಸಂಖ್ಯೆ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 15, currency: "INR", is_free: false, notes: { en: "Free for viewing; Rs 15 for digitally signed official download.", hi: "देखना मुफ्त, डिजिटल हस्ताक्षर वाली प्रति 15 रुपये।", kn: "ವೀಕ್ಷಿಸಲು ಉಚಿತ, ಅಧಿಕೃತ ಸಹಿ ಇರುವ ಪ್ರತಿಯನ್ನು ಪಡೆಯಲು ರೂ 15." }, varies_by: null },
    steps: [
      { step_number: 1, title: { en: "Open Bhoomi portal", hi: "bhoomi.karnataka.gov.in खोलें", kn: "bhoomi.karnataka.gov.in ತೆರೆಯಿರಿ" }, description: { en: "Visit landrecords.karnataka.gov.in/service2.", hi: "भूमि पोर्टल पर जाएँ", kn: "ಭೂಮಿ ಪೋರ್ಟಲ್‌ಗೆ ಭೇಟಿ ನೀಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Select Land Location & Survey Number", hi: "जिला, गांव और सर्वे नंबर चुनें", kn: "ಸ್ಥಳ ಮತ್ತು ಸರ್ವೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ" }, description: { en: "Choose Surnoc, Hissa number, and Period.", hi: "हिस्सा नंबर और वर्ष चुनें", kn: "ಹಿಸ್ಸಾ ಸಂಖ್ಯೆ ಮತ್ತು ವರ್ಷ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "View details & download signed RTC", hi: "आरटीसी देखें और डाउनलोड करें", kn: "ಆರ್‌ಟಿಸಿ ವೀಕ್ಷಿಸಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Pay Rs 15 to get government watermarked copy.", hi: "15 रुपये का भुगतान कर डाउनलोड करें", kn: "ರೂ 15 ಪಾವತಿಸಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://landrecords.karnataka.gov.in/service2",
    official_url_label: { en: "Bhoomi Land Records Portal", hi: "भूमि लैंड रिकॉर्ड्स पोर्टल", kn: "ಭೂಮಿ ಲ್ಯಾಂಡ್ ರೆಕಾರ್ಡ್ಸ್ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Digitally signed RTC is downloaded immediately. It contains owner name, extent of land, soil type, and crop details.", hi: "तुरंत डाउनलोड योग्य।", kn: "ತಕ್ಷಣ ಡೌನ್‌ಲೋಡ್ ಮಾಡಬಹುದು." },
    troubleshooting: [],
    source_notes: "Revenue Department, Government of Karnataka",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["rtc", "pahani", "bhoomi", "land record", "survey number", "karnataka land records", "mutation extract"],
  },

  // 16. Police Clearance Certificate (PCC - Karnataka Police)
  {
    id: "svc-police-clearance-certificate",
    slug: "police-clearance-certificate",
    name: { en: "Police Verification / Clearance Certificate (PCC)", hi: "पुलिस सत्यापन / क्लीयरेंस प्रमाणपत्र (PCC)", kn: "ಪೊಲೀಸ್ ಪರಿಶೀಲನೆ / ಕ್ಲಿಯರೆನ್ಸ್ ಪ್ರಮಾಣಪತ್ರ (PCC)" },
    category: "police-verification",
    tier: 3,
    state: "karnataka",
    description: { en: "Apply for a Police Verification Certificate (PVC / PCC) for employment, passport, tenant verification, or emigration in Karnataka via Seva Sindhu or Karnataka State Police portal.", hi: "कर्नाटक पुलिस या सेवा सिंधु पोर्टल द्वारा नौकरी या पासपोर्ट के लिए पुलिस क्लीयरेंस सर्टिफिकेट बनवाएं।", kn: "ಉದ್ಯೋಗ, ಪಾಸ್‌ಪೋರ್ಟ್ ಅಥವಾ ಬಾಡಿಗೆದಾರರ ಪರಿಶೀಲನೆಗಾಗಿ ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಕ್ಲಿಯರೆನ್ಸ್ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ." },
    short_description: { en: "Get your background and police clearance certificate in Karnataka.", hi: "पुलिस वेरिफिकेशन सर्टिफिकेट ऑनलाइन अप्लाई करें।", kn: "ಪೊಲೀಸ್ ಪರಿಶೀಲನೆ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ." },
    eligibility_rules: null,
    questions: [
      { id: "purpose", type: "select", label: { en: "What is the purpose of the certificate?", hi: "प्रमाणपत्र का उद्देश्य क्या है?", kn: "ಪ್ರಮಾಣಪತ್ರದ ಉದ್ದೇಶವೇನು?" }, options: [{ value: "job", label: { en: "Employment / Job verification", hi: "नौकरी / रोजगार", kn: "ಉದ್ಯೋಗ ಪರಿಶೀಲನೆ" } }, { value: "passport", label: { en: "Passport / Foreign Visa", hi: "पासपोर्ट / विदेश वीजा", kn: "ಪಾಸ್‌ಪೋರ್ಟ್ / ವೀಸಾ" } }, { value: "tenant", label: { en: "Tenant verification", hi: "किरायेदार सत्यापन", kn: "ಬಾಡಿಗೆದಾರರ ಪರಿಶೀಲನೆ" } }], required: true, eligibility_relevant: false },
    ],
    required_documents: [
      { id: "aadhaar", name: { en: "Aadhaar Card", hi: "आधार कार्ड", kn: "ಆಧಾರ್ ಕಾರ್ಡ್" }, status: "required" },
      { id: "photo", name: { en: "Passport-size photograph", hi: "पासपोर्ट साइज फोटो", kn: "ಭಾವಚಿತ್ರ" }, status: "required" },
      { id: "address_proof", name: { en: "Proof of residence in Karnataka", hi: "निवास प्रमाण", kn: "ನಿವಾಸ ಪುರಾವೆ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 250, currency: "INR", is_free: false, notes: { en: "Rs 250 for individuals; Rs 500 for foreign verification.", hi: "व्यक्तिगत के लिए 250 रुपये, विदेश के लिए 500 रुपये।", kn: "ವೈಯಕ್ತಿಕಕ್ಕೆ ರೂ 250, ವಿದೇಶಕ್ಕೆ ರೂ 500." }, varies_by: "purpose" },
    steps: [
      { step_number: 1, title: { en: "Apply on Seva Sindhu or KSP Police portal", hi: "सेवा सिंधु या पुलिस पोर्टल पर जाएँ", kn: "ಸೇವಾ ಸಿಂಧು ಅಥವಾ ಪೊಲೀಸ್ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ" }, description: { en: "Visit sevasindhu.karnataka.gov.in or ksp.karnataka.gov.in.", hi: "पोर्टल पर विवरण भरें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ವಿವರ ಭರ್ತಿ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Upload documents & pay verification fee", hi: "दस्तावेज़ अपलोड करें और शुल्क दें", kn: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಶುಲ್ಕ ಪಾವತಿಸಿ" }, description: { en: "Pay official fee via net banking / UPI.", hi: "शुल्क का ऑनलाइन भुगतान करें", kn: "ಆನ್‌ಲೈನ್ ಶುಲ್ಕ ಪಾವತಿಸಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Local Police Station verification", hi: "थाने द्वारा सत्यापन", kn: "ಸ್ಥಳೀಯ ಪೊಲೀಸ್ ಠಾಣೆಯಿಂದ ಪರಿಶೀಲನೆ" }, description: { en: "Officer checks criminal record databases and local antecedents.", hi: "पुलिस रिकॉर्ड की जांच", kn: "ಕ್ರಿಮಿನಲ್ ರೆಕಾರ್ಡ್ ಪರಿಶೀಲನೆ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Download digitally signed PCC", hi: "डिजिटल प्रमाणपत्र डाउनलोड करें", kn: "ಡಿಜಿಟಲ್ ಸಹಿ ಇರುವ PCC ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, description: { en: "Certificate signed by DSP / Commissioner is available for download.", hi: "पोर्टल से डाउनलोड करें", kn: "ಪೋರ್ಟಲ್‌ನಿಂದ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://ksp.karnataka.gov.in",
    official_url_label: { en: "Karnataka State Police Portal", hi: "कर्नाटक पुलिस आधिकारिक पोर्टल", kn: "ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ಅಧಿಕೃತ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "PCC is issued in 15–21 working days after police station clearance.", hi: "15–21 कार्य दिवसों में जारी।", kn: "15–21 ದಿನಗಳಲ್ಲಿ ಲಭ್ಯ." },
    troubleshooting: [],
    source_notes: "Karnataka State Police Citizen Services Charter",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["police clearance", "pcc", "character certificate", "police verification", "ksp", "seva sindhu police"],
  },

  // 17. Marriage Certificate Registration
  {
    id: "svc-marriage-certificate",
    slug: "marriage-certificate",
    name: { en: "Marriage Certificate Registration (Kaveri)", hi: "विवाह पंजीकरण प्रमाणपत्र (कावेरी)", kn: "ವಿವಾಹ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ (ಕಾವೇರಿ)" },
    category: "family-marriage",
    tier: 3,
    state: "karnataka",
    description: { en: "Register marriage under the Hindu Marriage Act or Special Marriage Act through Kaveri Online Services at your local Sub-Registrar Office in Karnataka.", hi: "कावेरी पोर्टल पर आवेदन करके उप-पंजीयक कार्यालय में विवाह पंजीकरण कराएं।", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್ ಮೂಲಕ ಸ್ಥಳೀಯ ಉಪನೋಂದಣಾಧಿಕಾರಿ ಕಚೇರಿಯಲ್ಲಿ ವಿವಾಹ ನೋಂದಣಿ ಮಾಡಿಸಿಕೊಳ್ಳಿ." },
    short_description: { en: "Register your marriage and get an official Marriage Certificate in Karnataka.", hi: "कर्नाटक में विवाह प्रमाणपत्र बनवाएं।", kn: "ವಿವಾಹ ನೋಂದಣಿ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ." },
    eligibility_rules: {
      all: [
        { field: "groom_age_21", operator: "equals", value: true, message: "Groom must be at least 21 years of age" },
        { field: "bride_age_18", operator: "equals", value: true, message: "Bride must be at least 18 years of age" },
      ],
    },
    questions: [
      { id: "groom_age_21", type: "boolean", label: { en: "Is the groom at least 21 years of age?", hi: "क्या दूल्हे की आयु 21 वर्ष या उससे अधिक है?", kn: "ವರನಿಗೆ ಕನಿಷ್ಠ 21 ವರ್ಷ ವಯಸ್ಸಾಗಿದೆಯೇ?" }, required: true, eligibility_relevant: true },
      { id: "bride_age_18", type: "boolean", label: { en: "Is the bride at least 18 years of age?", hi: "क्या दुल्हन की आयु 18 वर्ष या उससे अधिक है?", kn: "ವಧುವಿಗೆ ಕನಿಷ್ಠ 18 ವರ್ಷ ವಯಸ್ಸಾಗಿದೆಯೇ?" }, required: true, eligibility_relevant: true },
    ],
    required_documents: [
      { id: "wedding_invitation", name: { en: "Wedding Invitation Card or Temple / Church / Nikah certificate", hi: "शादी का निमंत्रण पत्र या धार्मिक प्रमाण", kn: "ವಿವಾಹ ಆಹ್ವಾನ ಪತ್ರಿಕೆ ಅಥವಾ ದೇವಸ್ಥಾನ/ಚರ್ಚ್/ನಿಕಾಹ್ ಪತ್ರ" }, status: "required" },
      { id: "couple_photos", name: { en: "Marriage ceremony photographs & joint passport photo", hi: "विवाह समारोह की तस्वीरें और संयुक्त फोटो", kn: "ವಿವಾಹದ ಭಾವಚಿತ್ರಗಳು" }, status: "required" },
      { id: "age_address_both", name: { en: "Aadhaar / Passport / 10th marksheet for both bride and groom", hi: "दूल्हा-दुल्हन दोनों का आधार और आयु प्रमाण", kn: "ವಧು ಮತ್ತು ವರ ಇಬ್ಬರ ಆಧಾರ್ ಹಾಗೂ ವಯಸ್ಸಿನ ದಾಖಲೆ" }, status: "required" },
      { id: "witnesses", name: { en: "Identity and address proof of 3 adult witnesses", hi: "3 गवाहों के पहचान पत्र", kn: "3 ಸಾಕ್ಷಿದಾರರ ಗುರುತಿನ ಚೀಟಿ" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 120, currency: "INR", is_free: false, notes: { en: "Official government registration fee ~Rs 120 (Rs 50-100 fine if registered after 30 days).", hi: "पंजीकरण शुल्क लगभग 120 रुपये।", kn: "ಅಧಿಕೃತ ನೋಂದಣಿ ಶುಲ್ಕ ಸುಮಾರು ರೂ 120." }, varies_by: null },
    steps: [
      { step_number: 1, title: { en: "Submit details on Kaveri Online Services", hi: "कावेरी पोर्टल पर फॉर्म भरें", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಭರ್ತಿ ಮಾಡಿ" }, description: { en: "Visit kaverionline.karnataka.gov.in and select 'Marriage Registration'.", hi: "पोर्टल पर विवरण दर्ज करें", kn: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ವಿವರ ಭರ್ತಿ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Book appointment slot at Sub-Registrar Office", hi: "अपॉइंटमेंट स्लॉट बुक करें", kn: "ಉಪನೋಂದಣಾಧಿಕಾರಿ ಕಚೇರಿಯಲ್ಲಿ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ" }, description: { en: "Select convenient date for in-person appearance.", hi: "तारीख चुनें", kn: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Appear before Sub-Registrar with 3 witnesses", hi: "3 गवाहों के साथ उप-पंजीयक के समक्ष उपस्थित हों", kn: "3 ಸಾಕ್ಷಿದಾರರೊಂದಿಗೆ ಕಚೇರಿಗೆ ಹಾಜರಾಗಿ" }, description: { en: "Sign the marriage register in presence of Sub-Registrar.", hi: "रजिस्ट्रार के समक्ष हस्ताक्षर करें", kn: "ನೋಂದಣಾಧಿಕಾರಿ ಮುಂದೆ ಸಹಿ ಮಾಡಿ" }, is_online: false, is_offline: true },
      { step_number: 4, title: { en: "Receive original Marriage Certificate", hi: "विवाह प्रमाणपत्र प्राप्त करें", kn: "ವಿವಾಹ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ" }, description: { en: "Certificate is issued on the spot or within 3 working days.", hi: "प्रमाणपत्र तुरंत या 3 दिनों में जारी", kn: "ಸ್ಥಳದಲ್ಲೇ ಅಥವಾ 3 ದಿನಗಳಲ್ಲಿ ಪ್ರಮಾಣಪತ್ರ ವಿತರಣೆ" }, is_online: false, is_offline: true },
    ],
    official_url: "https://kaverionline.karnataka.gov.in",
    official_url_label: { en: "Kaveri Online Services Portal", hi: "कावेरी ऑनलाइन पोर्टल", kn: "ಕಾವೇರಿ ಆನ್‌ಲೈನ್ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Official certificate is handed over on the same day or downloadable online with barcode verification.", hi: "उसी दिन जारी या ऑनलाइन डाउनलोड योग्य।", kn: "ಅಂದೇ ವಿತರಣೆ ಅಥವಾ ಆನ್‌ಲೈನ್ ಡೌನ್‌ಲೋಡ್." },
    troubleshooting: [],
    source_notes: "Karnataka Stamps and Registration Department",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["marriage certificate", "marriage registration", "kaveri marriage", "sub registrar marriage", "vivaha pramanapatra"],
  },

  // 18. EPF / UAN Services (EPFO India)
  {
    id: "svc-epf-uan-services",
    slug: "epf-uan-services",
    name: { en: "EPF / UAN Services (PF Withdrawal & Transfer)", hi: "ईपीएफ / यूएएन सेवाएं (पीएफ निकासी और ट्रांसफर)", kn: "ಇಪಿಎಫ್ / ಯುಎಎನ್ ಸೇವೆಗಳು (ಪಿಎಫ್ ಹಿಂಪಡೆಯುವಿಕೆ ಮತ್ತು ವರ್ಗಾವಣೆ)" },
    category: "employment-benefits",
    tier: 3,
    state: "karnataka",
    description: { en: "Manage your Employee Provident Fund (EPF), activate Universal Account Number (UAN), transfer PF balance, or submit online withdrawal claims on EPFO Member Portal.", hi: "ईपीएफओ पोर्टल पर अपना पीएफ बैलेंस चेक करें, क्लेम करें या यूएएन एक्टिवेट करें।", kn: "EPFO ಸದಸ್ಯ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಪಿಎಫ್ ಹಿಂಪಡೆಯಿರಿ, ವರ್ಗಾಯಿಸಿ ಅಥವಾ UAN ಸಕ್ರಿಯಗೊಳಿಸಿ." },
    short_description: { en: "Check PF balance, withdraw, or transfer EPF online via Member Portal.", hi: "पीएफ बैलेंस, ट्रांसफर और विड्रॉल ऑनलाइन करें।", kn: "ಪಿಎಫ್ ಬ್ಯಾಲೆನ್ಸ್ ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಹಿಂಪಡೆಯಿರಿ." },
    eligibility_rules: null,
    questions: [],
    required_documents: [
      { id: "uan_aadhaar", name: { en: "Active UAN linked with Aadhaar and Verified Bank Account", hi: "आधार और बैंक खाते से लिंक यूएएन", kn: "ಆಧಾರ್ ಮತ್ತು ಬ್ಯಾಂಕ್ ಲಿಂಕ್ ಆಗಿರುವ UAN" }, status: "required" },
    ],
    conditional_documents: [],
    official_fee: { amount: 0, currency: "INR", is_free: true, notes: { en: "All EPFO online member services are completely free.", hi: "ईपीएफओ की ऑनलाइन सेवाएं बिल्कुल मुफ्त हैं।", kn: "ಎಲ್ಲಾ EPFO ಸೇವೆಗಳು ಸಂಪೂರ್ಣ ಉಚಿತ." }, varies_by: null },
    steps: [
      { step_number: 1, title: { en: "Login to EPFO Unified Member Portal", hi: "unifiedportal-mem.epfindia.gov.in पर लॉगिन करें", kn: "EPFO ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ" }, description: { en: "Log in with UAN and password.", hi: "यूएएन और पासवर्ड से लॉगिन करें", kn: "UAN ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ ಲಾಗಿನ್ ಮಾಡಿ" }, is_online: true, is_offline: false },
      { step_number: 2, title: { en: "Verify KYC (Aadhaar, PAN & Bank Details)", hi: "केवाईसी सत्यापित करें", kn: "KYC ಪರಿಶೀಲಿಸಿ" }, description: { en: "Ensure your bank account has approved employer DSC signature.", hi: "बैंक विवरण सही होना चाहिए", kn: "ಬ್ಯಾಂಕ್ ವಿವರಗಳು ಅನುಮೋದನೆಗೊಂಡಿರಬೇಕು" }, is_online: true, is_offline: false },
      { step_number: 3, title: { en: "Submit Online Claim (Form 19 / 10C / 31)", hi: "ऑनलाइन क्लेम सबमिट करें", kn: "ಆನ್‌ಲೈನ್ ಕ್ಲೈಮ್ ಸಲ್ಲಿಸಿ" }, description: { en: "Select Full Settlement (Form 19) or Advance (Form 31).", hi: "विड्रॉल प्रकार चुनें", kn: "ಕ್ಲೈಮ್ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ" }, is_online: true, is_offline: false },
    ],
    official_url: "https://unifiedportal-mem.epfindia.gov.in/memberinterface/",
    official_url_label: { en: "EPFO Unified Member Portal", hi: "EPFO सदस्य पोर्टल", kn: "EPFO ಸದಸ್ಯ ಪೋರ್ಟಲ್" },
    what_happens_after: { en: "Claims are approved and credited directly to your bank account within 7–10 working days.", hi: "7–10 दिनों में बैंक खाते में राशि ट्रांसफर।", kn: "7–10 ದಿನಗಳಲ್ಲಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮಾ." },
    troubleshooting: [],
    source_notes: "Employees' Provident Fund Organisation",
    verification_status: "verified",
    last_verified_on: "2026-08-01",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-08-01T00:00:00Z",
    version: 1,
    active: true,
    keywords: ["epf", "pf", "epfo", "uan", "pf withdrawal", "pf balance", "provident fund"],
  },
];

export function getSeededServices(): Service[] {
  return SEED_SERVICES;
}

export function getSeededServiceBySlug(slug: string): Service | null {
  return SEED_SERVICES.find((s) => s.slug === slug) ?? null;
}

export function getSeededServiceById(id: string): Service | null {
  return SEED_SERVICES.find((s) => s.id === id) ?? null;
}

export function getSeededCategories(): ServiceCategory[] {
  return SEED_CATEGORIES;
}
